### ISSUE TITLE
Rect Button borderCollor

### ISSUE THREAD

**Issue by luizandrends** [software-mansion/react-native-gesture-handler#1022] opened 2020-04-06 18:21 UTC
The RectButton dosen't work with the style attribute borderCollor on android.

`const styles = StyleSheet.create({
  isTagged: {
    borderColor: '#27ae60',
  },
  isNotTagged: {
    borderColor: '#fff',
  },
})
`

**Comment by jakub-gonet** [comment] 2020-08-24 14:09
Duplicate of #477.

**Closed by jakub-gonet** 2020-08-24 14:09 UTC
