### ISSUE TITLE
Gesture handlers don't get updated properly to falsy values

### ISSUE THREAD

**Issue by radex** [software-mansion/react-native-gesture-handler#599] opened 2019-05-09 06:29 UTC
Say I have:

```
<PanGestureHandler ... activeOffsetY={ foo ? 5 : undefined }>
```

if foo changes to false, the gesture handler won't get updated properly. I'd expect it to change to null/default value, but nothing is actually sent to native side, since it's stripped in JS for optimization. So the handler stays configured with 5.

Similarly:

```
<PanGestureHandler ... activeOffsetY={ foo ? [1, 2] : 5 }>
```

won't work properly.

**Workaround**: Use `[-10000, 10000]` as placeholders for fail offset and `[-1, 1]` as placeholder for active offset

**Comment by radex** [comment] 2019-05-09 15:14
Would it be a reasonable solution to just pass the whole config over the bridge w/o stripping it on _updates_ ?

**Comment by wcandillon** [comment] 2020-08-18 07:52
@radex Thank you for the proposed workaround, it helped me.

**Comment by jakub-gonet** [comment] 2020-09-03 18:47
Duplicate of #440.

**Closed by jakub-gonet** 2020-09-03 18:47 UTC
Labels: Gesture handlers
