### ISSUE TITLE
Implement maxDistFromEdge to only activate PanGestureHandler if user swipes from screen edge

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-gesture-handler#1309] opened 2021-01-19 13:30 UTC
## Description

We're developing an app which has a similar layout as Snapchat: A horizontal tab view which contains 5 views where the user can swipe between to switch views.

![](https://user-images.githubusercontent.com/15199031/105031007-f2ab5700-5a54-11eb-880f-12c967bf232e.png)

Notice how there is a map on the first (left) screen. Since the map also has a pan gesture handler, we have overlapping gesture handlers. (`<PanGestureHandler>` for swiping between screens, native `UIPanGestureResponder` for map panning).

Snapchat solves this quite elegantly, by only allowing a **horizontal swipe gesture** if the user started the gesture from the right screen edge, everything else is a **map pan gesture**, which we're also trying to achieve.

Unfortunately, this is currently not possible, since the map (react-native-maps or mapbox-gl) uses native `UIPanGestureRecognizer`s and we have no way of interacting with those handlers using the RNGH API - meaning it is unpredictable which gesture handler picks up the gesture.

https://user-images.githubusercontent.com/15199031/105031667-ea075080-5a55-11eb-9ff5-b87a3d3d29f0.mov

I've given this some thought on how we could possibly implement this feature, and came up with the following solutions (ordered from best to worst imo):

1. Create a `maxDistFromEdge` property for `<PanGestureHandler>`s, which only activates the handler if the user started the gesture from within `{maxDistFromEdge}`px the view bounds. So if we set said property to `20`, the `<PanGestureHandler>` only activates if the user started the gesture from within `20`px or less of the view's (screen's) left, top, right or bottom bounds. Ideally we want this to be an object, so you can for example specify:
    ```jsx
    <PanGestureHandler
      maxDistFromEdge={{ left: 0, top: 0, right: 20, bottom: 0 }} />
    ```
2. Edit the map view native module to give the native `UIPanGestureRecognizer` a margin-right of `20`px so it doesn't trigger if the user starts the gesture from within 20px of the right screen border, and then we somehow create a ref and pass that to the horizontal swipe gesture `<PanGestureHandler>`'s `waitFor` prop. (not very flexible)
3. Edit the map view native module to give the native `UIPanGestureRecognizer` a margin-right of `20`px, and edit our horizontal swiper setup to give the `<PanGestureHandler>` a margin left of `SCREEN_WIDTH - 20`, so they don't visually overlap (bad and ugly idea)

For solution 1 (my fav), [this answer on stackoverflow](https://stackoverflow.com/a/14809014/5281431) shows how easy this would be implemented on iOS.

I'd love to hear some opinions here, cc @jakub-gonet @kmagiera @osdnk . If you have better and simpler ideas, I'd love to hear 'em. If not, I could start implementing the `maxDistFromEdge` property on iOS, but I'll need some help for the android side.

**Comment by mrousavy** [comment] 2021-01-19 14:52
I'm working on `minDistFromEdge` here: https://github.com/software-mansion/react-native-gesture-handler/pull/1310

**Comment by jakub-gonet** [comment] 2021-08-23 04:35
May be related to #465.

**Comment by kmagiera** [comment] 2022-03-31 11:27
Based on comments on #1310 I understand the issue is no longer current and seems like it is ok to close it.

In case anyone finds this in the future, with gesture-handler 2.0 API we now provide a mechanism called "manual activation" (see more here: https://docs.swmansion.com/react-native-gesture-handler/docs/next/api/gestures/manual-gesture) which allows for recognition logic to be implemented on JS side and run synchronously. This eliminates the need for more obscure activation criteria and is ideal for cases like this one.

**Closed by kmagiera** 2022-03-31 11:27 UTC
Labels: Feature request, Area: Gesture handlers
