### ISSUE TITLE
IOS build issue with the new updation of 1.9.0, #Error Property 'allowedScrollTypesMask' not found on object of type 'RNBetterPanGestureRecognizer *'

### ISSUE THREAD

**Issue by Shahulul** [software-mansion/react-native-gesture-handler#1239] opened 2020-11-26 07:58 UTC
Ios gives build issue Property 'allowedScrollTypesMask' not found on object of type 'RNBetterPanGestureRecognizer *'

Just compile and run the project after updation of react-native gesture-handler from 1.8.0 to 1.9.0. It gives build error in IOS.

### Screenshots
![Screenshot 2020-11-26 at 12 45 49 PM](https://user-images.githubusercontent.com/75004013/100322891-ed003a80-2fea-11eb-8423-0976eeddd737.png)

## Steps To Reproduce

1.
Run the IOS application after updating react-native gesture-module to 1.9.0

## Package versions

- React:16.11.0
- React Native:0.62.2
- React Native Gesture Handler:1.9.0

**Comment by jakub-gonet** [comment] 2020-11-26 09:01
Duplicate of #1235.

Please upgrade your xcode version.

**Closed by jakub-gonet** 2020-11-26 09:01 UTC
