### ISSUE TITLE
ScrollView refresh control gesture when released outside of the screen bounds doesn't work the same as React Native ScrollView

### ISSUE THREAD

**Issue by brentvatne** [software-mansion/react-native-gesture-handler#560] opened 2019-04-12 22:14 UTC
Demonstrated in this gif. First, I pull to refresh with the ScrollView exported from react-native. Next, I pull to refresh with the ScrollView exported from react-native-gesture-handler. Each time I release the gesture outside of the bounds of the screen of the device. Notice that with the react-native ScrollView that when I release, the refresh control animation begins, but it does not when I release with the react-native-gesture-handler ScrollView.

![scrollview](https://user-images.githubusercontent.com/90494/56068873-53ace380-5d35-11e9-9e52-18c639d1e575.gif)

Repro: https://snack.expo.io/@notbrent/vigorous-ice-cream. The issue seems to be that `onRefresh` never fires.

**Comment by vvusts** [comment] 2019-06-03 11:26
@brentvatne have you managed to solve this?
I have same situation I have `scrollview` filled with items and on pull to refresh I clear those items and `RefreshControl` is visible.
But when I scroll to bottom and press button that call same action `RefreshControl` is not visible until I touch and pull down a little bit.

**Comment by aznoisib** [comment] 2019-07-16 22:58
I also have a problem scrolling freezes the problem is on certain android devices I can send videos if you want, maybe inside core componnet of react native

**Comment by brentvatne** [comment] 2019-07-19 18:12
I haven't, I've just been using react-native's ScrollView instead for now

**Comment by aznoisib** [comment] 2019-07-20 13:47
This bug is not just a scrollview display, all the scrolling components freeze



Tested on react native app

1. expo
2. reqct native paper
3. codepad (my experiment app)

issues: yes



tested on native mobile app
1. android example

issues: no

video sample 1
https://www.dropbox.com/s/5mh8aje1cv0e7q6/mobizen_20190720_125215.mp4?dl=0

sample videos 2
https://www.dropbox.com/s/z5eupip3s9ozmqa/mobizen_20190720_125825.mp4?dl=0

Device info
https://www.dropbox.com/s/4mn6tswvlums1hm/Screenshot_Setelan_20190720-124232.png?dl=0

**Comment by harrisrobin** [comment] 2019-12-20 10:44
Experiencing this as well using version `~1.5.2`

**Comment by Evan-Younan** [comment] 2020-05-19 18:26
Still experiencing this in `1.6.1`

**Comment by Evan-Younan** [comment] 2020-07-20 18:01
It seems like this has been fixed on the native side. After working on an unrelated issue, I decided to update some Android native packages under `app/buid/build.gradle`:

```
implementation 'androidx.appcompat:appcompat:1.3.0-alpha01'
implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
```

This seems to have fixed the issue for me.

**Closed** 2020-09-03 18:32 UTC
Labels: Android
