### ISSUE TITLE
<Touchable*> styling is not compatible with React Native Touchables

### ISSUE THREAD

**Issue by radex** [software-mansion/react-native-gesture-handler#607] opened 2019-05-14 09:24 UTC
RNGH Touchables have a different behavior from RN Touchables when styling — making them not drop-in compatible.

Take for example:

this is the behavior of RN TouchableOpacity (and of RNGH `BaseButton`):

<img width="503" alt="Captura de pantalla 2019-05-14 11 02 45" src="https://user-images.githubusercontent.com/183747/57686487-f8bf2280-7639-11e9-8fe8-fcb8cbf39c1a.png">

this is the behavior of RNGH touchables:

<img width="527" alt="Captura de pantalla 2019-05-14 11 03 01" src="https://user-images.githubusercontent.com/183747/57686489-f957b900-7639-11e9-8ca2-6f266ee66dcd.png">

the yellow box is a touchable with `flex: 1`.

The problem is that all RNGH Touchables render two wrapped views:

https://github.com/kmagiera/react-native-gesture-handler/blob/baf2ba72ea4fca22a11b507cffb4ee94f0126480/touchables/GenericTouchable.js#L258-L266

The styles are applied to the child view, so applying `flex: 1` doesn't do what one would expect.

I _think_ the only way to avoid this incompatibility is to render just one native view. This should also be a little more performant.

I'm willing to help with implementation (at least on JS+iOS side), but I would need some basic pointers as to how to make `RawButton` accept `View` props…

**Comment by vinnyHero** [comment] 2019-07-03 18:10
any update on this ? @kmagiera @brentvatne

**Comment by njdancer** [comment] 2019-11-26 06:03
@radex #854 is not exactly what you’ve proposed but does allow for a workaround.

In my use case, supplying '''containerStyle={{ flex: 1 }}''' to an RNGH Touchable along with my existing '''style''' prop, mirrors the native behaviour.

**Comment by mjarraya** [comment] 2020-03-02 13:19
If not fixed, this needs at minimum to be mentioned in the docs

**Comment by lukebars** [comment] 2021-04-29 08:41
Is there any progress on this one? Looks like crucial part of gesture handler's future, to be as consistent to react-native styling as possible.

**Comment by j-piasecki** [comment] 2022-05-12 12:50
`containerStyle` prop has been added to Gesture Handler's Touchables quite a while ago in https://github.com/software-mansion/react-native-gesture-handler/pull/854. I'll close the issue because using that prop will solve the problem of not being able to style the outer view, and there is a lot of open issues regarding styling of Touchables and buttons coming from the same root cause.

**Closed by j-piasecki** 2022-05-12 12:50 UTC
Labels: Important, Area: Touchable, BugBash 31.03
