### ISSUE TITLE
TurboModuleRegistry.getEnforcing(...): 'RNGestureHandlerModule' could not be found

### ISSUE THREAD

**Issue by lynajiang** [software-mansion/react-native-gesture-handler#2847] opened 2024-04-04 01:10 UTC
### Description

In process of installing @gorhom/bottom-sheet package, I was installing the gesture-handler package. I followed all the steps of installation which included adding import statements (import 'react-native-gesture-handler') to both App.tsx and index.js. In app.tsx, GestureHandlerRootView wraps the contents. The code breaks even when I comment out the @gorhom/bottom-sheet package and components.

Of course in debugging this whole debacle, 
1. Deleted the pod files, podfile.lock, and node_modules folder. 
2. Pod install and npm install in respective folders
3. Clean build folder in xcode
4. Deleted DerivedData
5. Rebuild

Since this is very similar to #2749, I've tried all the solutions there. Nothing has worked.

### Steps to reproduce

1. Install @gorhom/bottom-sheet, react-native-reanimated, react-native-gesture-handler
2. Finish installation steps for all three packages

### Snack or a link to a repository

https://github.com/lynajiang/Project-Lemon-Issue-Code.git

### Gesture Handler version

2.16.0

### React Native version

0.73.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

Real device

### Device model

iPhone 14 Pro iOS 17.4

### Acknowledgements

Yes

**Comment by m-bert** [comment] 2024-04-04 09:07
Hi, I've just build your app on both, iOS simulator and real device and everything works fine (though there was an error that `useMemo` was not imported). Are you sure you've properly cleaned your environment? Make sure to delete `pods` and `node_modules`

**Comment by lynajiang** [comment] 2024-04-05 07:06
Yes. I am sure I properly cleaned the environment. I uninstalled and reinstalled a couple of times. If I were to comment out "import 'react-native-gesture-handler';" in both App.tsx and index.js as well as import { GestureHandlerRootView } from 'react-native-gesture-handler'; in App.tsx (and commenting out GestureHandlerRootView). I would not get any errors. This of course would make the bottomsheet component error since the Gesture Handler module is not sufficiently installed.

**Comment by m-bert** [comment] 2024-04-05 09:16
In that case could you provide more information about this error? Like stack trace or full error message?

**Comment by m-bert** [comment] 2024-04-05 12:10
Also, have you encountered this issue before? Did it happen after upgrading gesture handler (or react native) version?

**Comment by lynajiang** [comment] 2024-04-05 18:34
The full error message is:
 ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGestureHandlerModule' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["PlatformConstants","LogBox","Timing","AppState","SourceCode","BlobModule","WebSocketModule","SettingsManager","DevSettings","RedBox","Networking","Appearance","DevLoadingView","UIManager","DeviceInfo"],"TurboModules":[],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","BugReporting","HeadlessJsTaskSupport","RNGestureHandlerModule"]}, js engine: hermes
 LOG  Running "Lemon" with {"rootTag":1,"initialProps":{}}
 ERROR  Invariant Violation: "Lemon" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes



And I have never used react-gesture-handler before. I had just installed the most up-to-date version of both react-native and react-gesture-handler packages.

**Comment by lynajiang** [comment] 2024-04-05 18:47
I also have pushed a cleaner version of the code.

**Comment by anucreative** [comment] 2024-04-06 20:10
I had the same trouble as you @lynajiang (new app with latest `react-native` : `0.73.6` and latest `react-native-gesture-handler` : `2.16.0`. Downgrading to `2.15.0` unblocked me.

**Comment by lynajiang** [comment] 2024-04-07 04:08
@anucreative Thank you! After downgrading gesture-handler to 2.15.0, it worked.

**Comment by m-bert** [comment] 2024-04-08 06:33
Though downgrading may help, it is not a solution that we recommend. I will keep this issue open until we find out what causes that problem.

**Comment by naitik-erpbuddies** [comment] 2024-04-15 09:01
I am also facing the same issue

**Comment by shubhamjajoo** [comment] 2024-04-18 05:36
I am also facing same... Will try downgrading if it works for me.

**Comment by patricktelnoni** [comment] 2024-04-26 16:37
I am currently facing the same issue here. Is this beacuse dependency problem during instalation, because i use react 18 on my project.. Here is the log result upon installing rect-native-gesture-handler. Please note that after i user yard, the package installed in my node_module project yet i get the  ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGestureHandlerModule' could not be found.

Here is the error upon installing react-native-gesture-handler
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: AwesomeProject@0.0.1
npm ERR! Found: @types/react@18.3.0
npm ERR! node_modules/@types/react
npm ERR!   dev @types/react@"^18.2.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @types/react@"^16.9.19" from native-base@3.3.1
npm ERR! node_modules/native-base
npm ERR!   native-base@"3.3.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/patricktelnoni/.npm/_logs/2024-04-26T16_34_16_030Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/patricktelnoni/.npm/_logs/2024-04-26T16_34_16_030Z-debug-0.log
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: AwesomeProject@0.0.1
npm ERR! Found: @types/react@18.3.0
npm ERR! node_modules/@types/react
npm ERR!   dev @types/react@"^18.2.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @types/react@"^16.9.19" from native-base@3.3.1
npm ERR! node_modules/native-base
npm ERR!   native-base@"3.3.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/patricktelnoni/.npm/_logs/2024-04-26T16_34_16_030Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/patricktelnoni/.npm/_logs/2024-04-26T16_34_16_030Z-debug-0.log

**Comment by C2418M31** [comment] 2024-05-19 06:26
I experience the same, tried downloading to 2.15.0 from 2.16.2. It is working when running npm start, but when I tried to convert it to aar and upload to a native android. this error shows up. I hope someone can help me on this.

`Unhandled SoftException
                                                                                       com.facebook.react.bridge.ReactNoCrashSoftException: Tried to access onWindowFocusChange while context is not ready
                                                                                       	at com.facebook.react.runtime.ReactHostImpl.onWindowFocusChange(ReactHostImpl.java:674)
                                                                                       	at com.facebook.react.ReactDelegate.onWindowFocusChanged(ReactDelegate.java:194)
                                                                                       	at com.facebook.react.ReactActivityDelegate.onWindowFocusChanged(ReactActivityDelegate.java:175)
                                                                                       	at com.facebook.react.ReactActivity.onWindowFocusChanged(ReactActivity.java:128)
                                                                                       	at androidx.appcompat.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:125)
                                                                                       	at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1788)
                                                                                       	at android.view.View.dispatchWindowFocusChanged(View.java:15933)
                                                                                       	at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1509)
                                                                                       	at android.view.ViewRootImpl.dispatchFocusEvent(ViewRootImpl.java:4059)
                                                                                       	at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:3963)
                                                                                       	at android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged(Unknown Source:0)
                                                                                       	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:5954)
                                                                                       	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5862)
                                                                                       	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                       	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                       	at android.os.Looper.loop(Looper.java:294)
                                                                                       	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                       	at java.lang.reflect.Method.invoke(Native Method)
                                                                                       	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                       	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)`
                                                                                       	
                                                                                       	
`Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGestureHandlerModule' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: true. TurboModule interop: true. Modules loaded: {"NativeModules":[],"TurboModules":["PlatformConstants","DeviceInfo","DeviceEventManager","BlobModule","NativeAnimatedModule"],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","RedBox","BugReporting","HeadlessJsTaskSupport","NativeReactNativeFeatureFlagsCxx","RNGestureHandlerModule"]}`

**Comment by themikan** [comment] 2024-05-29 08:10
> I experience the same, tried downloading to 2.15.0 from 2.16.0. It is working when running npm start, but when I tried to convert it to aar and upload to a native android. this error shows up. I hope someone can help me on this.我也有同样的经历，尝试从2.16.0下载到2.15.0。它在运行 npm start 时工作，但是当我尝试将其转换为 aar 并上传到本机 android 时。出现此错误。我希望有人能在这方面帮助我。
> 
> **Gesture Handler version 手势处理程序版本** 2.16.0
> 
> **React Native version 反应本机版本** 0.74.1
> 
> **Platform 平台** Android  安卓
> 
> **Type 类型** AAR
> 
> `Unhandled SoftException com.facebook.react.bridge.ReactNoCrashSoftException: Tried to access onWindowFocusChange while context is not ready at com.facebook.react.runtime.ReactHostImpl.onWindowFocusChange(ReactHostImpl.java:674) at com.facebook.react.ReactDelegate.onWindowFocusChanged(ReactDelegate.java:194) at com.facebook.react.ReactActivityDelegate.onWindowFocusChanged(ReactActivityDelegate.java:175) at com.facebook.react.ReactActivity.onWindowFocusChanged(ReactActivity.java:128) at androidx.appcompat.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:125) at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1788) at android.view.View.dispatchWindowFocusChanged(View.java:15933) at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1509) at android.view.ViewRootImpl.dispatchFocusEvent(ViewRootImpl.java:4059) at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:3963) at android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged(Unknown Source:0) at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:5954) at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5862) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:205) at android.os.Looper.loop(Looper.java:294) at android.app.ActivityThread.main(ActivityThread.java:8177) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)`
> 
> `Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGestureHandlerModule' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: true. TurboModule interop: true. Modules loaded: {"NativeModules":[],"TurboModules":["PlatformConstants","DeviceInfo","DeviceEventManager","BlobModule","NativeAnimatedModule"],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","RedBox","BugReporting","HeadlessJsTaskSupport","NativeReactNativeFeatureFlagsCxx","RNGestureHandlerModule"]}`

I have same problem

**Comment by YiguiDing** [comment] 2024-05-29 09:50
same error

**Comment by Developer-Mohali** [comment] 2024-05-29 13:40
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNPermissions' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["PlatformConstants","LogBox","Timing","AppState","SourceCode","BlobModule","WebSocketModule","DevSettings","DevToolsSettingsManager","Networking","Appearance","DevLoadingView","HeadlessJsTaskSupport","UIManager","DeviceInfo","ImageLoader","SoundManager","IntentAndroid","DeviceEventManager","RNCWebView"],"TurboModules":[],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","RedBox","BugReporting","LinkingManager","RNVectorIcons","RNPermissions"]}, js engine: hermes
 LOG  Running "BaseTemplete" with {"rootTag":41}
 ERROR  Invariant Violation: "BaseTemplete" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

Getting the same issue. 
Anyone Please help on this

My react-native : 0.74.1
 "react-native-gesture-handler": "2.15.0",

**Comment by MrNapcae** [comment] 2024-06-02 11:02
same error

**Comment by raquelnishimoto** [comment] 2024-06-21 22:23
Note that this answer is aimed at ios. 
There is no need to downgrade the package. Try installing the pod
`cd ios && npx pod deintegrate && npx pod install && cd ..`

Then, go to Xcode and clean the project:
`Product -> Clean build folder`
Finally, in Xcode build and run the project by clicking the play button (arrow forward).

**Comment by Ratna99** [comment] 2024-06-27 02:59
For me, I had nx mono repo. And I have installed react-native-gesture-handler in my main package.json file (I was not using it directly but other package:react-navigation was using it). So, react-native-gesture-handler was missing in package.json of my mobile app directory. So, I added "react-native-gesture-handler": "*" in package.json inside my mobile directory, pod install in ios and then did a build run-ios. Then finally it worked.

**Comment by Anusha-mathur** [comment] 2024-07-17 06:52
same error, If anyone know how to fix this please help.

Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGestureHandlerModule' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: true. TurboModule interop: true. Modules loaded: {"NativeModules":[],"TurboModules":["PlatformConstants","LogBox","SourceCode","AppState","BlobModule","WebSocketModule","DevSettings","DevToolsSettingsManager","Networking","Appearance","DevLoadingView","DeviceInfo","ImageLoader","SoundManager","IntentAndroid","DeviceEventManager","NativeAnimatedModule","I18nManager"],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","RedBox","BugReporting","HeadlessJsTaskSupport","LinkingManager","NativeReactNativeFeatureFlagsCxx","RNCSafeAreaContext","ReanimatedModule","RNGestureHandlerModule"]}
 (NOBRIDGE) LOG  Running "trendlyne_app" with {"rootTag":11,"initialProps":{},"fabric":true}

**Comment by vedantb2** [comment] 2024-08-11 21:49
I'm also having this issue after building the APK for my app, and react-native-gesture-handler is the cause of this.

**Comment by m-bert** [comment] 2024-08-16 11:14
Hi @lynajiang! Do you still experience this issue? If so, could you attach `node_modules` to reproduction? We would like to take a closer look into them

**Comment by m-bert** [comment] 2024-08-16 16:18
Also, to all who are currently seeing this issue. If it happens after upgrading `react-native` version, did you use [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/)?

**Comment by ghostgarrix** [comment] 2024-08-19 20:56
@m-bert Yes, happened to me after Rn upgrade from `0.74.2` to `0.75.1` (latest) using the RN upgrade helper

**Comment by jmazier-j2d** [comment] 2024-08-22 16:39
Same here, upgrading from.... RN 0.66 to 0.74 (don't judge me !) and mostly following the upgrade helper. Can provide more info if needed.

**Comment by lovely-tiger** [comment] 2024-09-05 08:30
> @anucreative Thank you! After downgrading gesture-handler to 2.15.0, it worked.
Hey, @lynajiang 
Please show your jest.config.ts file.

**Comment by jmazier-j2d** [comment] 2024-09-05 21:23
Any update here ? I'm still struggling with this issue (only on android) and it's just driving me crazy has it's preventing from releasing a huge update :(

I've even tried to remove all reference to RNGestureHandler but somehow, the error sticks... even after clearing all caches...

**Comment by IMSBuSu** [comment] 2024-09-18 09:56
> > I experience the same, tried downloading to 2.15.0 from 2.16.0. It is working when running npm start, but when I tried to convert it to aar and upload to a native android. this error shows up. I hope someone can help me on this.我也有同样的经历，尝试从2.16.0下载到2.15.0。它在运行 npm start 时工作，但是当我尝试将其转换为 aar 并上传到本机 android 时。出现此错误。我希望有人能在这方面帮助我。
> > **Gesture Handler version 手势处理程序版本** 2.16.0
> > **React Native version 反应本机版本** 0.74.1
> > **Platform 平台** Android  安卓
> > **Type 类型** AAR
> > `Unhandled SoftException com.facebook.react.bridge.ReactNoCrashSoftException: Tried to access onWindowFocusChange while context is not ready at com.facebook.react.runtime.ReactHostImpl.onWindowFocusChange(ReactHostImpl.java:674) at com.facebook.react.ReactDelegate.onWindowFocusChanged(ReactDelegate.java:194) at com.facebook.react.ReactActivityDelegate.onWindowFocusChanged(ReactActivityDelegate.java:175) at com.facebook.react.ReactActivity.onWindowFocusChanged(ReactActivity.java:128) at androidx.appcompat.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:125) at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1788) at android.view.View.dispatchWindowFocusChanged(View.java:15933) at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1509) at android.view.ViewRootImpl.dispatchFocusEvent(ViewRootImpl.java:4059) at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:3963) at android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged(Unknown Source:0) at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:5954) at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5862) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:205) at android.os.Looper.loop(Looper.java:294) at android.app.ActivityThread.main(ActivityThread.java:8177) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)`
> > `Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGestureHandlerModule' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: true. TurboModule interop: true. Modules loaded: {"NativeModules":[],"TurboModules":["PlatformConstants","DeviceInfo","DeviceEventManager","BlobModule","NativeAnimatedModule"],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","RedBox","BugReporting","HeadlessJsTaskSupport","NativeReactNativeFeatureFlagsCxx","RNGestureHandlerModule"]}`
> 
> I have same problem

do you find any way ? my whatsapp +91 9213120419

**Comment by darkmoor24** [comment] 2024-09-18 18:20
I'm new posting comments on github, I don't know if theres any kind of rule to refer a link.. but I solved this error based on this issue resolution 

#2749

**Comment by m-bert** [comment] 2024-10-10 14:20
One more question, please look at [this repro](https://github.com/m-bert/rngh-turbo-module-repro) and tell me whether you can see this error or not.

To run it simply:

1. Run `yarn` command in root
2. Run `bundle install && bundle exec pod install` in `ios `directory

For `Fabric`, change `newArchEnabled` flag in `gradle.properties` in `android` directory:

```diff
-newArchEnabled=false
+newArchEnabled=true
```

And for `ios` set `RCT_NEW_ARCH_ENABLED` flag to `1`:

`RCT_NEW_ARCH_ENABLED=1 bundle install && bundle exec pod install`

Please tell me if you see this error in my reproduction.

**Comment by petertoth-dev** [comment] 2024-10-20 01:36
@m-bert still cannot fix this issue and we are totally stuck installing a very basic feature for 4 days now, what's going on? Please support newer react-native versions!

**Comment by petertoth-dev** [comment] 2024-10-20 02:14
@darkmoor24  WHAT exactly did you do to solve it? You linked the whole thread and it's about testing running jest, and not running the project itself

**Comment by petertoth-dev** [comment] 2024-10-20 02:29
weird thing happened .... I am struggling with this for 4 days, back and forth, and today I've made a mistake and it fixed it (not sure why).

So I tried this:
1. cd ios
2. `RCT_NEW_ARCH_ENABLED=1 pod install`

this messed up everything, nothing was working so I wanted to go back to the original method, but I've made a typo (I've found it in my bash history):
I run this:
3. `RCT_NEW_ARCH_ENABLED=1=0 pod install`

For some reason everything is working now LOL :D 

Package versions that worked:

```
     "react-native": "0.75.4",
     "react-native-gesture-handler": "2.20.0",
     "react-native-reanimated": "3.15.5",
```

**Comment by m-bert** [comment] 2024-10-21 07:27
Hi @petertoth-dev!

> Please support newer react-native versions!

We do support newer versions of React Native, as well as New Architecture

>I run this:
>3. `RCT_NEW_ARCH_ENABLED=1=0 pod install`
>
>For some reason everything is working now LOL :D

It works because now this variable is treated as string `1=0`, and `Podfile` enables `fabric` if it is equal to `1`. In other words, your app runs on `paper`.

**Comment by m-bert** [comment] 2024-10-21 08:12
Since this thread has now over 32 comments, we have to take some action. There were many suggested solutions, as well as other problems mentioned (like `Unhandled SoftException com.facebook.react.bridge.ReactNoCrashSoftException: Tried to access onWindowFocusChange while context is not ready`). At this point there's nothing we can do about this issue since the only reproduction works fine on our machines. I will close this issue because it seems that it is strongly connected to user setup and there's no generic solution.

If this issue is still bothering you, please open a new one. **_Before doing so_**, please first check if [this project](https://github.com/m-bert/rngh-turbo-module-repro) works fine. If it does, then the problem probably lies in your setup and there's not much that we can do about it. In that case you can contact as at [projects@swmansion.com](mailto:projects@swmansion.com). Otherwise, please **_remember to attach_** [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) (issues without working reproduction will be closed).

**Closed by m-bert** 2024-10-21 08:12 UTC
Labels: Platform: Android, Platform: iOS, Repro provided

**Comment by MobileMon** [comment] 2024-10-25 14:46
I'm also getting this same issue in an expo project

working when i run from expo GO but when i run the app in release mode directly from xcode i encounter the error

@m-bert

**Comment by SSL-ACTX** [comment] 2024-10-27 12:06
Same issue. It runs fine in Expo Go, but after building it... Got this issue...

**Comment by anasalaqeel** [comment] 2024-12-07 20:53
Hi everyone, Please refer to my answer here [](https://stackoverflow.com/a/79261382/12861001)

**Comment by nathanguigui** [comment] 2024-12-10 15:15
Upgrading to react-native `0.76.5` did the tricks and solved the issue

**Comment by m-bert** [comment] 2025-05-26 13:24
Hi! It's been a while and I think we've managed to find out what was causing this issue.

Turns out that if `react-native-gesture-handler` is not a direct dependency of app, `codegen` will not be run for it. You can see that in [this function ](https://github.com/facebook/react-native/blob/c93036ce7d0287d6961031f648da18492bcb020b/packages/react-native/scripts/codegen/generate-artifacts-executor/utils.js#L171). It means that if your app is using any library that has `react-native-gesture-handler` as `peerDependency`,  `react-native-gesture-handler` won't be linked and `codegen` will not detect it, even though it will be installed in `node_modules`. 

The solution to this problem is to simply add `react-native-gesture-handler` to your app dependency list. 

Kudos to @qwertychouskie for his investigation ❤

If the issue still persists, you can open new one. Please **_remember to attach_** [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

>[!CAUTION]
> As stated in [this comment](https://github.com/software-mansion/react-native-gesture-handler/issues/2847#issuecomment-2425936034) issues without working reproduction **_will be closed!_**
