### ISSUE TITLE
LongPressGestureHandle cancels when scrolling a FlatList

### ISSUE THREAD

**Issue by kundarmah** [software-mansion/react-native-gesture-handler#805] opened 2019-10-28 10:30 UTC
When LongPressGestureHandle is in `ACTIVE` State it works well even holding it for a long time. But once I use scrollToOffset it 
`CANCELS` it (-1) after a while.

```
        moveList = amount => {
		if (!this.scrolling) {
			return;
		}
		this.props.getFlatListRef().getNode().scrollToOffset({
			offset: this.props.scrollY + amount,
			animated: true,
		});

		requestAnimationFrame(() => {
			this.moveList(amount);
		});
	};
```

**Comment by jkadamczyk** [comment] 2020-09-01 13:11
Unfortunately I can't reproduce this issue. I will close this one until there is a minimal reproduction that I can try this on.

**Closed by jkadamczyk** 2020-09-01 13:11 UTC
Labels: Can't repro
