### ISSUE TITLE
Attempted import error: 'hoist-non-react-statics' does not contain a default export (imported as 'hoistNonReactStatics').

### ISSUE THREAD

**Issue by nicastelo** [software-mansion/react-native-gesture-handler#1003] opened 2020-03-13 21:26 UTC
Hi,

I'm using react-native-web & react-native-gesture-handler@1.6.0, and I'm not able to compile for web due to this crash.

<img width="1034" alt="Screen Shot 2020-03-13 at 18 18 05" src="https://user-images.githubusercontent.com/2942206/76660305-56244880-6557-11ea-932f-39ffb1031956.png">

iOS & Android compile fine.

Tested react-native-gesture-handler@1.5.3 and works fine on web, but it doesn't for iOS & Android.

Made this patch in order to bypass the error on the product I'm working on https://github.com/GoodDollar/GoodDAPP/pull/1422/files#diff-c7a931165435a8a40e02f9530590349f

**Comment by jakub-gonet** [comment] 2021-02-17 15:16
I'm afraid I couldn't reproduce it. [`hoist-non-react-statics` does have a default export](https://github.com/mridgway/hoist-non-react-statics/blob/f3de655212b47f20b9c6a27e89a60d23f358925a/src/index.js#L69) so this was maybe coming from an earlier version of this library?

I'm going to close this one since it's almost a year old. If you still experience this problem please reply or create a new issue.

**Closed by jakub-gonet** 2021-02-17 15:16 UTC
Labels: Bug, Platform: Web
