### ISSUE TITLE
Performance issue when using Swipable in flatlist

### ISSUE THREAD

**Issue by UsamaIkraam0099** [software-mansion/react-native-gesture-handler#1531] opened 2021-08-02 11:38 UTC
Performance issue when using Swipable in Flatlist 
## Steps To Reproduce

1.

## Package versions

- React: 17.0.1
- React Native: 0.64.2
- React Native Gesture Handler: 1.10.3

**Comment by jakub-gonet** [comment] 2021-08-02 13:27
Could you please expand on this one? Preferably with benchmarks and the code you used to show performance issues with Swipeables.

**Comment by tgreco** [comment] 2021-08-02 15:03
I notice the same performance issue.
Slow UI updates.

**Comment by UsamaIkraam0099** [comment] 2021-08-08 18:56
Basically i apply this on FlatList and when changing on any FlatList item like backgroundcolor or borderColor its slow and taking time but when I remove Swipeable FlatList working fine no issue there. I'll share some code

**Comment by alexstanbury** [comment] 2021-08-12 12:45
I'm seeing poor performance with Swipeable in a Flatlist too. It can be observed by using the swipeable demo from the example in this repo and increasing the number of data items in the Flatlist. For now I've had to switch over to react-native-interactable but I'd much rather be using this library.

**Comment by msageryd** [comment] 2021-12-28 17:06
I'm having this issue too.

As soon as I introduce Swipeable in my Flatlist items the list scrolls much less smoothly. I have a couple of 100 items with a thumbnail and av SVG pie chart. The list scrolls perfectly smooth without Swipeable.

I thought that maybe the flatlist had trouble measuring the height of Swipeable, so I wrapped it with a View with a constant height. This didn't solve the issue. I tried setting height on containerStyle as well as childrenContainerStyle, no difference.

I console.log:ed in the Swipeable source to see if it was re-rendering all the time, but it wasn't. Each Swipeable is rendered twice, but after that no more render is logged while I'm scrolling. I don't know why it renders twice, but this is not the problem anyway.

I'll go ahead and try https://github.com/wix/react-native-interactable instead.

I'd rather use react-native-gesture-handler since I'm using this lib in other places in my app. It would be really awesome if this issue could be solved somehow.

**Comment by msageryd** [comment] 2021-12-28 18:15
To illustrate the problem I have made two screen recordings from my iPhone X. The first recording is with a Swipeable wrapping the list items. When I scroll slowly, the performance problem is very visible. Actually, when looking at this I don't know if this really is a performance problem. It looks more lika some kind of layout problem.

The second recording is without Swipeable. Buttery smooth, as you can see.

I appologize for the crappy blurring. This is live client data which I cannot show. I have never used iMovie before, so it looks like sh-t.

**With Swipeable**
https://user-images.githubusercontent.com/4483085/147594877-91e6384b-dee4-41c4-99dc-cb22593de30f.mp4

**Without Swipeable**
https://user-images.githubusercontent.com/4483085/147594895-4eb82773-eca0-4b76-a5c2-03c193399afc.mp4

**Comment by Haider3iq** [comment] 2022-02-03 02:22
Hi @msageryd, I am running into same performance issues.... have you solved this please?

**Comment by tylercote** [comment] 2022-12-01 23:57
I also have this issue, and I think it may be related to some re-renders due to state changes that I am not causing.

![2022-12-01 18 56 32](https://user-images.githubusercontent.com/10457353/205183943-c28ad5e2-03fd-41cc-9cad-548745eef274.gif)

**Comment by pierroo** [comment] 2023-01-15 12:34
Is there any update about this performance issue?
Swipeable as of now is not usable in flatlist.

**Comment by 9903SV** [comment] 2023-08-18 05:14
@jakub-gonet 

We are also facing the same issue. We are using **`Swipeable`** in **Shopify's FlashList**. Is there any update regarding the performance issue?

**Comment by MensurRasic** [comment] 2023-08-23 22:40
Same issue here, any solution or alternative to Swipeable ?

**Comment by smfunder** [comment] 2023-09-15 18:40
Same here, I detected this using Shopify's FlashList with Swipeable. When they are together a fast scroll will generate blank areas, while removing Swipeable it works very smooth. Any suggestion or any replacement for Swipeable component?

**Comment by Acetyld** [comment] 2023-10-13 19:44
Same, are there any alternatives

**Comment by masonle2x2** [comment] 2023-12-20 04:54
I got same issue, any solution for it?

**Comment by crusherblack** [comment] 2024-02-12 03:40
after i take out swipable the perfomance back to normal, are there any alternatives?

**Comment by stassokolov1** [comment] 2024-03-07 21:36
@crusherblack @ngocle2497 @Acetyld @smfunder 
hello guys, check please code below, works much more smoothly for me
`
<Swipeable onSwipeableWillClose={() => setShowRightAction(false)} onActivated={() => setShowRightAction(true)} renderLeftActions={showRightAction ? renderLeftActions : undefined}>
...
</Swipeable>
`

**Comment by Acetyld** [comment] 2024-03-08 09:37
> @crusherblack @ngocle2497 @Acetyld @smfunder @UsamaIkraam0099 hello guys, check please code below, works much more smoothly for me `<Swipeable onSwipeableWillClose={() => setShowRightAction(false)} onActivated={() => setShowRightAction(true)} renderLeftActions={showRightAction ? renderLeftActions : undefined}> ... </Swipeable>`

Did you check performance / fps after implementing this For me it dropped to 30/40fps

**Comment by stassokolov1** [comment] 2024-03-08 10:55
@Acetyld 

Yes, I'm using FlashList and when i pass undefined to renderLeftActions it works more smoothly but not smooth like without Swipeable, which list you use?

**Comment by smfunder** [comment] 2024-03-08 15:41
hey @Acetyld @stassokolov1 and all the people here. I ended up using Interactable.View. And I use it in combination of FlashList and it is super smooth.

`  
import Interactable from 'react-native-interactable'

  const leftSwipe = (item) => {
    // NOTE: We are no longer using TouchableOpacity in a flat list because it created this issue:
    // https://github.com/facebook/react-native/issues/34376#issuecomment-1231324454
    return (
      <View>
        <Pressable onPress={handlePinUnPinCallback}>
          <FastImage style={styles.pinUnpinMsg} source={item?.isFavorite ? Images.UNPIN_MSG : Images.PIN_MSG} />
        </Pressable>
      </View>
    )
  }

return (
    <View>
      {leftSwipe(groupDetail)}
      <Interactable.View
        ref={swipeRef}
        horizontalOnly={true}
        dragEnabled={isEnableSwipe}
        snapPoints={[{ x: 100 }, { x: 0 }, { x: -150 }]}
        alertAreas={[{ id: 'leftArea', influenceArea: { left: 5 } }, { id: 'rightArea', influenceArea: { right: 5 } }]}
        onAlert={handleOnSwipeAlert}
       >
       <View> ****Content of the cell***** </View>
     </Interactable.View>
</View>

`

**Comment by smfunder** [comment] 2024-03-08 16:03
> > I ended up using Interactable.View. And I use it in combination of FlashList and it is super smooth.
> 
> This is exciting. Which specific `react-native-interactable` package are you using?

@rparrett I'm using  "react-native-interactable": "^2.0.1"
https://github.com/wix-incubator/react-native-interactable

**Comment by Acetyld** [comment] 2024-03-08 16:03
> > > I ended up using Interactable.View. And I use it in combination of FlashList and it is super smooth.
> > 
> > 
> > This is exciting. Which specific `react-native-interactable` package are you using?
> 
> @rparrett I'm using "react-native-interactable": "^2.0.1" https://github.com/wix-incubator/react-native-interactable

Does it work in expo dev build?

**Comment by smfunder** [comment] 2024-03-08 17:04
> > > > I ended up using Interactable.View. And I use it in combination of FlashList and it is super smooth.
> > > 
> > > 
> > > This is exciting. Which specific `react-native-interactable` package are you using?
> > 
> > 
> > @rparrett I'm using "react-native-interactable": "^2.0.1" https://github.com/wix-incubator/react-native-interactable
> 
> Does it work in expo dev build?

@Acetyld sorry I don't know, I'm not using expo.

**Comment by imyanglu** [comment] 2024-05-26 07:42
: (

**Comment by maksim-romanov** [comment] 2024-07-25 20:07
same problem for me!

**Comment by stichingsd-vitrion** [comment] 2024-07-26 08:37
Same here

**Comment by kkafar** [comment] 2024-07-26 08:46
Guys, I'm not on gesture-handler team, but I would recommend doing following for this issue to get attention of the maintainers:

1. properly describing the issue, with videos (if there are visual glitches), ideally benchmarks on **release** build profile of your app / example if you conducted some,
2. proper reproduction (a code snippet / repository with reproducer),
3. list of library versions you're using.

It would also be most likely beneficial to open a new issue that has above information in the description.

**Comment by j-piasecki** [comment] 2024-10-15 15:41
This issue seems to be describing exactly the same thing as https://github.com/software-mansion/react-native-gesture-handler/issues/3141, but that one is newer and has a better description and reproduction so I'll close this one.

**Closed by j-piasecki** 2024-10-15 15:41 UTC
Labels: Missing info, Area: Swipeable, BugBash 31.03
