### ISSUE TITLE
Unsupported top level event type "onGestureHandlerStateChange" dispatched

### ISSUE THREAD

**Issue by phyuthinkyi** [software-mansion/react-native-gesture-handler#849] opened 2019-11-23 03:59 UTC
currently i was using react native version 0.61.4.  and gesture handler version is 1.5.0.
![gesture](https://user-images.githubusercontent.com/58060930/69472718-1b49a980-0ddc-11ea-8d7e-a65981711107.png)
after that i was face with this issue. Error only shows in release mode not in developing mode.

**Comment by KrisShin** [comment] 2019-12-26 08:28
Same as mine

**Comment by shadow-boy** [comment] 2019-12-31 03:37
same as mine 
currently i was using react native version 0.61.4. and gesture handler version is 1.5.0.

**Comment by imaginasean** [comment] 2020-02-11 20:53
same here, ios, release mode only, same versions as @shadow-boy. Any one have a resolution?

**Comment by krudos** [comment] 2020-04-15 09:10
same issue

**Comment by jakub-gonet** [comment] 2020-11-02 14:05
Duplicate of #320.

[This solution may help you](https://github.com/software-mansion/react-native-gesture-handler/issues/320#issuecomment-443815828).

**Closed by jakub-gonet** 2020-11-02 14:05 UTC
Labels: iOS
