### ISSUE TITLE
Setting failOffsetY through panViewRef.current.setNativeProps causes activeOffsetX to not work

### ISSUE THREAD

**Issue by haibert** [software-mansion/react-native-gesture-handler#1658] opened 2021-09-25 18:10 UTC
## Description
Setting failOffsetY through panViewRef.current.setNativeProps causes activeOffsetX to not work

Im trying to activate the panGestureHandler only when the scroll offset of my flat list is at 0, The logic i'm using works fine except one thing. As the comments in the code show, when setting failOffsetY: [-0.1, 0.1] it renders activeOffsetX: [-999, 0.1] useless and my x axis does not get activated. Are we not allowed to put these parameters together? I'm having a hard time finding where the issue is arising from. 

## Steps To Reproduce
Please look at the snack provided: https://snack.expo.dev/@haibert/activeoffsety

### Expected behavior
I want to be able to assigning the failOffsetY of the Y axis to [-0.1, 0.1] while also assigning the activeOffsetX of the X axis to [-999, 0.1]

### Actual behavior
failOffsetY gets assigned but activeOffsetX does not get assigned. 
ONLY when I comment out failOffsetY: [-0.1, 0.1] ,  activeOffsetX: [-999, 0.1] gets assigned. 
## Snack or minimal code example
https://snack.expo.dev/@haibert/activeoffsety
```
const toggleGestureActivation = useCallback((shouldLock = false) => {
        panViewRef.current.setNativeProps({
            ...(shouldLock
                ? {
                      activeOffsetY: [-999, 0.1],
                      failOffsetY: [-0.1, 999],
                      //this doesn't run
                      activeOffsetX: [-999, 0.1],
                  }
                : {
                      activeOffsetY: [-100, 100],
                      failOffsetY: [-0.1, 0.1],
                      //this doesn't run
                      activeOffsetX: [-999, 0.1],
                  }),
        })
    }, [])
```

## Package versions

- React:  16.13.1
- React Native: 0.63
- React Native Gesture Handler: ~1.10.2
- Expo : 42

**Comment by haibert** [comment] 2021-09-29 17:17
Anyone ? :')

**Comment by j-piasecki** [comment] 2022-04-21 13:55
Hi! I tried your snack and I think it's working. Here's how it looked:

https://user-images.githubusercontent.com/21055725/164472828-7cd482e3-2849-4d12-809e-3cbac7bb35b9.mp4

Is something wrong here?
As a sidenote, I don't think [you should be using `setNativeProps` on `PanGestureHandler`](https://reactnative.dev/docs/direct-manipulation#composite-components-and-setnativeprops).

**Comment by haibert** [comment] 2022-04-21 14:13
Hi I forgot to mention that it doesn't work on iOS. Looks like you're trying on an android correct ?

**Comment by j-piasecki** [comment] 2022-04-21 14:58
Yes, I that was on Android, I tried the iOS and I it looks like it's working (almost):

https://user-images.githubusercontent.com/21055725/164483065-32365f2f-6a97-4568-843d-00efcdc276f7.mp4

I needed to uncomment the props on `PanGestureHandler` and changed `failOffsetY: [-0.1, 0.1]` to `failOffsetY: [-20, 20]` in the callback. Also, it seems like `scrollEventThrottle={0}` results in different behavior on iOS, so I had to set it to `1`.

**Comment by j-piasecki** [comment] 2022-04-28 13:09
If I understand correctly, it's working as intended on both platforms so I'll close the issue. If that's not the case, feel free to reopen it.

**Closed by j-piasecki** 2022-04-28 13:09 UTC
Labels: Area: Gesture handlers
