### ISSUE TITLE
[IOS] nested scrollViews, when scrolling the top scrollview it passes touches to the parent scrollview which make the keyboard dismiss  ?

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-gesture-handler#1282] opened 2020-12-21 04:55 UTC
## Description

when nesting 2 scrollviews, when you scroll the child scrollview the input is out of focus and the keyboard dismisses, is there anyway that I can avoid that ? 

scrollview 
 > scrollview << when this scrollview is scrolled the input is out of focus.
  > ..subviews 
 > input
 

- React: 16.13.1
- React Native: 0.63.4
- React Native Gesture Handler: ^1.9.0

**Comment by jakub-gonet** [comment] 2021-08-23 04:13
Duplicate of #1269.

**Closed by jakub-gonet** 2021-08-23 04:13 UTC
