### ISSUE TITLE
TouchableOpacity doesn't render as expected in Flatlist 

### ISSUE THREAD

**Issue by ayRatul** [software-mansion/react-native-gesture-handler#523] opened 2019-03-16 23:00 UTC
As the docs says , the touchableopacity is supposed to be a drop-in replacement of the RN one. But , if creating a flatlist (in my case with 3 columns) , and using a simple `<TouchableOpacity style={{ flex: 1 , aspectRatio: 1 ,backgroundColor:'red' }}/>` as a renderItem . The list never gets populated (it remains at 0 height). So i suppose that the support of aspect ratio, or flex might be failing at some point. because if i use the RN touchableopacity , it renders as expected. a Flatlist filled with red squares

**Comment by thanh90** [comment] 2020-04-01 01:58
I did try with TouchableOpacity and it didn't seem to work. so I put a View inside a TouchableOpacity. and it's done

**Comment by jakub-gonet** [comment] 2020-09-03 13:05
Duplicate of #607.

**Closed by jakub-gonet** 2020-09-03 13:05 UTC
