### ISSUE TITLE
Values with native driver not set correctly when chaining pan gesture event with decay animation

### ISSUE THREAD

**Issue by louispvb** [software-mansion/react-native-gesture-handler#220] opened 2018-06-21 21:30 UTC
When I try to run an Animated.decay on a value using the native driver after a pan gesture has acted on it, the animated value is not set correctly causing a view to jump.

I've created a demonstration here: https://snack.expo.io/BkqYD9Kb7

When running on iOS, if you drag the red circle and let the kinetic sliding animation finish, the next touch will pan it correctly, but when letting go the red circle jumps erratically. The blue circle running the JS driver does not have this issue.

**Comment by jakub-gonet** [comment] 2020-11-26 16:48
To be honest I'm not sure that even JS example is working as intended.

![Screen Recording 2020-11-26 at 17 38 02](https://user-images.githubusercontent.com/12465392/100376222-6a3da680-300f-11eb-817a-0690b72403b8.gif)

It also jumps around.

Also given that the issue is more than two years old I'll close it. 

If you want to reopen this please respond.

**Closed by jakub-gonet** 2020-11-26 16:48 UTC
Labels: Can repro
