### ISSUE TITLE
Warning when closing Reanimated Swipeable

### ISSUE THREAD

**Issue by atheck** [software-mansion/react-native-gesture-handler#3044] opened 2024-08-13 12:01 UTC
### Description

I use the new Reanimated version of the Swipeable component. When I call `close()` on the ref, a warning is shown:

![screenshot-1723548719660](https://github.com/user-attachments/assets/ad132b3e-ecda-45bd-939a-a6f6ef45b870)

### Steps to reproduce

```tsx
const swipeableRef = useRef<SwipeableMethods>(null);

const renderRightActions = () => {
  return (
    <IconButton
      onPress={() => {
        swipeableRef.current?.close();
        onPress();
      }}
    />
  );
};

return <Swipeable
  ref={swipeableRef}
  renderRightActions={renderRightActions}
/>
```

### Snack or a link to a repository

See Steps to reproduce

### Gesture Handler version

2.18.1

### React Native version

0.73.9

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Acknowledgements

Yes

**Comment by latekvo** [comment] 2024-08-13 14:57
Hey @atheck, thank you for reporting this issue.

Could you please let me know if [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/3045) resolves your issue?

I couldn't reproduce this error with the code you provided, if you were to continue to encounter this issue, could you please provide us with an independently working reproduction code? It looks like the fragment you provided is an extract from a larger component.

**Comment by atheck** [comment] 2024-08-13 15:03
Many thanks for the quick response. I'll give it a try.

Yes indeed, the code I provided is a fragment of a larger component. I tried to create a snack, but I didn't get it to work with current versions of the packages "react-native-gesture-handler" and "react-native-reanimated".

If your PR is not working for me I try to create a working reproduction.

**Comment by atheck** [comment] 2024-08-13 15:22
It works, no warning anymore. Thank you @latekvo!

**Comment by rifad4u** [comment] 2024-08-14 15:22
@latekvo I'm also facing this warning when closing a row. Please make the PR live.

**Closed** 2024-08-21 21:21 UTC
Labels: Platform: Android, Missing repro
