### ISSUE TITLE
Play store report details crash in app only in production

### ISSUE THREAD

**Issue by mahamaad** [software-mansion/react-native-gesture-handler#1916] opened 2022-03-06 19:59 UTC
### **I have this error occurrence most time in android **

**com.facebook.react.bridge.JSApplicationIllegalArgumentException: 
  at com.swmansion.gesturehandler.react.RNGestureHandlerModule.tryInitializeHandlerForReactRootView (RNGestureHandlerModule.kt:456)
  at com.swmansion.gesturehandler.react.RNGestureHandlerModule.attachGestureHandler (RNGestureHandlerModule.kt:363)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:188)
  at com.facebook.react.bridge.queue.NativeRunnable.run (Native Method)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:27)
  at android.os.Looper.loop (Looper.java:246)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:226)
  at java.lang.Thread.run (Thread.java:923)**

### Platforms

- [ ] iOS

- [x] Android

- [ ] Web

## Steps To Reproduce

1.

## Package versions

- React:
- React Native:
- React Native Gesture Handler:
- React Native Reanimated:

**Comment by j-piasecki** [comment] 2022-03-28 13:11
Hi! This looks like a duplicate of https://github.com/software-mansion/react-native-gesture-handler/issues/1675. I'll close this issue to keep the discussion in one place, but it's possible that https://github.com/software-mansion/react-native-gesture-handler/pull/1936 will solve the problem.

**Closed by j-piasecki** 2022-03-28 13:11 UTC
Labels: Missing info, Platform: Android, Missing repro
