### ISSUE TITLE
[Android] Expo App crashes on the touch event

### ISSUE THREAD

**Issue by IaroslavTernovy** [software-mansion/react-native-gesture-handler#983] opened 2020-02-19 19:16 UTC
Hi guys, 
When I trying to use one of these 1.5.0-1.6.0 version, android expo app crashes on any touch event. I found [this](https://github.com/software-mansion/react-native-gesture-handler/issues/841#issuecomment-559498002) suggestion, but it doesn't work for me. 
  
> 02-19 20:11:29.718 23032 23032 E InputEventReceiver: Exception dispatching input event.
02-19 20:11:29.718 23032 23032 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI: java.lang.IllegalStateException: Already prepared or hasn't been reset
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at abi36_0_0.host.exp.exponent.modules.api.components.gesturehandler.GestureHandler.prepare(GestureHandler.java:7)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at abi36_0_0.host.exp.exponent.modules.api.components.gesturehandler.GestureHandlerOrchestrator.recordHandlerIfNotPresent(GestureHandlerOrchestrator.java:8)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at abi36_0_0.host.exp.exponent.modules.api.components.gesturehandler.GestureHandlerOrchestrator.recordViewHandlersForPointer(GestureHandlerOrchestrator.java:5)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at abi36_0_0.host.exp.exponent.modules.api.components.gesturehandler.GestureHandlerOrchestrator.traverseWithPointerEvents(GestureHandlerOrchestrator.java:12)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at abi36_0_0.host.exp.exponent.modules.api.components.gesturehandler.GestureHandlerOrchestrator.extractGestureHandlers(GestureHandlerOrchestrator.java:5)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at abi36_0_0.host.exp.exponent.modules.api.components.gesturehandler.GestureHandlerOrchestrator.onTouchEvent(GestureHandlerOrchestrator.java:4)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at abi36_0_0.host.exp.exponent.modules.api.components.gesturehandler.react.RNGestureHandlerRootHelper.dispatchTouchEvent(RNGestureHandlerRootHelper.java:2)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at abi36_0_0.host.exp.exponent.modules.api.components.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.java:1)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at abi36_0_0.host.exp.exponent.modules.api.components.gesturehandler.react.RNGestureHandlerEnabledRootView.dispatchTouchEvent(RNGestureHandlerEnabledRootView.java:2)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:461)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.app.Activity.dispatchTouchEvent(Activity.java:3465)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at b.a.o.i.dispatchTouchEvent(WindowCallbackWrapper.java:1)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:419)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.View.dispatchPointerEvent(View.java:12774)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5305)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5105)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4673)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4639)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4779)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4647)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4836)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4673)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4639)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4647)
02-19 20:11:29.722 23032 23032 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)

**Comment by MaksymVoronin** [comment] 2020-02-19 19:46
+1

**Comment by edosssa** [comment] 2020-02-20 22:50
Same here

**Comment by alandeivson** [comment] 2020-02-21 21:08
I'm having the problem using stack navigator from react navigation... (It depends on gesture-handler 1.5)

**Comment by rodriguezmanu** [comment] 2020-02-27 16:49
+1

**Comment by edosssa** [comment] 2020-02-27 16:52
@alandeivson I ultimately had to downgrade expo to SDK 35

**Comment by hamidfzm** [comment] 2020-02-28 11:50
Another solution is to stop using expo :). It's very unstable and app sizes are too large.

**Comment by alandeivson** [comment] 2020-02-28 15:28
Did you try expo in the last 3 months? It improved a lot :).
I think it's a really good alternative, especially for MVPs.

**Comment by andrepcg** [comment] 2020-02-28 21:15
https://github.com/react-navigation/react-navigation/issues/6919

**Comment by alandeivson** [comment] 2020-02-29 20:03
> [react-navigation/react-navigation#6919](https://github.com/react-navigation/react-navigation/issues/6919)

It works!
Just add:
` "packagerOpts": {
    "sourceExts": [
      "expo.ts",
      "expo.tsx",
      "expo.js",
      "expo.jsx",
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "wasm",
      "svg"
    ]
  }`
In your app.json
(https://github.com/react-navigation/react-navigation/issues/6919#issuecomment-592093015)

**Comment by Ferin79** [comment] 2020-04-01 12:48
> @alandeivson I had the same problem and ultimately had to downgrade expo to SDK 35. You could try that in the interim.

How to downgrade expo sdk to 35 from 36

**Comment by sourabhgupta901** [comment] 2020-06-13 11:31
> > @alandeivson I had the same problem and ultimately had to downgrade expo to SDK 35. You could try that in the interim.
> 
> How to downgrade expo sdk to 35 from 36

Just change "expo": "~36.0.0" to 35.0.0 in your package.json file.

**Comment by jakub-gonet** [comment] 2020-08-24 15:26
Duplicate of #841.

**Closed by jakub-gonet** 2020-08-24 15:26 UTC
