### ISSUE TITLE
Use react-native-gesture-handler with react-native 0.62 without enabling androidx

### ISSUE THREAD

**Issue by ebiba-dp** [software-mansion/react-native-gesture-handler#806] opened 2019-10-28 16:16 UTC
I run `npx jetify -r` and also when I start application I use `react-native run-android --no-jetifier`
After that I get this error:
`error: package android.support.annotation does not exist`

I have a clean project where I have only `react-native` and `react-native-gesture-handler`

My project is not ready yet to move to androidx and I wanna update react-native but without migrating to androidx and I am facing issues with react-native-gesture-handler.

I think it should be backward-compatible so we can be able to use it without having to migrate over androidx.

**Comment by jakub-gonet** [comment] 2020-08-25 15:23
Duplicate of #743.

**Closed by jakub-gonet** 2020-08-25 15:23 UTC
