### ISSUE TITLE
Bug with permissions dialog and position

### ISSUE THREAD

**Issue by ahce** [software-mansion/react-native-gesture-handler#386] opened 2018-12-15 23:47 UTC
## Description

- Position bug: The drawer is behind the button:
![image](https://user-images.githubusercontent.com/12452003/50048330-d4b9de00-00a7-11e9-9942-69bac2bc6146.png)
- Position fix: Set zIndex
![image](https://user-images.githubusercontent.com/12452003/50048337-121e6b80-00a8-11e9-8e1f-9d2b9bcf9a4a.png)
- Permission dialog bug: The drawer in close mode is visible behind the dialog, this occur in special situations
  - Form 1:
    - First: press next up to value 2
    - Second: focus the textinput and open keyboard
    - Third: press next again
  - Form 2:
    - First: press next or back button repeatedly

**Steps**
![image](https://user-images.githubusercontent.com/12452003/50048367-e18b0180-00a8-11e9-9caf-14e16736d214.png)

**Result**
![image](https://user-images.githubusercontent.com/12452003/50048359-c0c2ac00-00a8-11e9-877a-111635f3c5a0.png)

## Note
This bugs don't occur with react-native-drawer-layout-polyfill.
In the demo, comment and uncomment the imports for switch the drawers.
![image](https://user-images.githubusercontent.com/12452003/50048410-10ee3e00-00aa-11e9-873b-8572bdd9cbb6.png)

## Environment
- react: 16.6.3
- react-native: 0.57.8
- react-native-gesture-handler: 1.0.12
- phone: Nokia 5 Android 8.1

## Demo
[RNGH-DrawerLayout-Bug](https://github.com/ahce/RNGH-DrawerLayout-Bug)

**Comment by osdnk** [comment] 2018-12-18 13:45
@brentvatne

**Comment by ahce** [comment] 2018-12-18 19:21
@brentvatne Thanks for your reply.

1. Yes, the problem is the elevation, where zIndex is the fix.

2. Special situations are those reported in the steps of Form 1 and 2 where the drawer is closed.

Please test my repo [RNGH-DrawerLayout-Bug](https://github.com/ahce/RNGH-DrawerLayout-Bug)

**Comment by ahce** [comment] 2018-12-24 23:12
@brentvatne the bug when drawer is closed and is visible behind the alert, don't occur with useNativeAnimations set in false.
It is possible to set useNativeAnimations to false by default?

**Comment by osdnk** [comment] 2018-12-26 21:47
@ahce, I don't want to change `useNativeAnimations` to `false`. It's not a point of this library. Will try to figure it out

**Comment by ahce** [comment] 2019-02-18 06:06
@brentvatne @osdnk I found an easier way to reproduce the bug. Check my repo [RNGH-DrawerLayout-Bug](https://github.com/ahce/RNGH-DrawerLayout-Bug) (dependencies updated to the latest).
I also found a possible solution, they are changes in 3 lines ([11](https://github.com/ahce/RNGH-DrawerLayout-Bug/blob/master/DrawerLayoutFixed.js#L11), [74](https://github.com/ahce/RNGH-DrawerLayout-Bug/blob/master/DrawerLayoutFixed.js#L74), [524](https://github.com/ahce/RNGH-DrawerLayout-Bug/blob/master/DrawerLayoutFixed.js#L524)), please check this.

**Comment by sign2k** [comment] 2019-03-12 21:44
I am experiencing the same problem (using react-native-navigation 3.3.2 + react-native-gesture-handler 1.1.0). My app navigates to a new screen and checks some Android permissions after mounting the screen component.
```
PermissionsAndroid.requestMultiple([
                "android.permission.ACCESS_FINE_LOCATION",
                "android.permission.ACCESS_COARSE_LOCATION",
                "android.permission.BLUETOOTH",
                "android.permission.BLUETOOTH_ADMIN"])
```
The drawer appears behind the android action dialog although it should not be visible at all.
```useNativeAnimations: false``` solves the problem but of course is not the best solution.

**Comment by ahce** [comment] 2019-03-13 04:44
@sign2k Can you test this [DrawerLayout](https://github.com/ahce/RNGH-DrawerLayout-Bug/blob/master/DrawerLayoutFixed.js)?

**Comment by sign2k** [comment] 2019-03-14 09:05
> @sign2k Can you test this [DrawerLayout](https://github.com/ahce/RNGH-DrawerLayout-Bug/blob/master/DrawerLayoutFixed.js)?

Tested it - seems not to help in my case. I replaced the offical "DrawerLayout.js" with your file.

**Comment by ahce** [comment] 2019-03-16 04:05
@sign2k 
The problem occurs when there is a render after the dialog is opened. 
In my [repo](https://github.com/ahce/RNGH-DrawerLayout-Bug), DrawerLayout as PureComponent avoids rendering when the keyboard is hidden, after trying to share the text, but it is not enough for all cases.

**Comment by maxwedwards** [comment] 2019-04-03 15:13
I've also got an app that requests permissions after navigating to a screen and it opens the drawer while the permission dialog is up.

**Comment by alburdette619** [comment] 2019-04-04 18:44
I'm having this issue too.  Should the `missing info` label be taken off?  It seems like @ahce has verified it and the cause pretty well.

**Comment by dvhchuot** [comment] 2019-06-24 08:26
useNativeAnimations: false, working for me!

**Comment by nash2196** [comment] 2019-09-08 11:39
What is the fix for this? This is still an issue.

**Comment by KAngel7** [comment] 2019-09-10 09:42
I faced the same issue "the drawer appears behind the android action dialog" with "react-native-gesture-handler": "^1.2.0" and "react-navigation": "3.2.0" but some devices works and some are not. Not sure where it come from, please help

**Comment by cayodonatti** [comment] 2019-10-08 21:10
Same problem here as of rn 0.61, rngh 1.4.1

**Comment by pravin-maan** [comment] 2019-10-23 05:33
thanks
useNativeAnimations:false,
  it's working

**Comment by CoolCola** [comment] 2019-10-28 02:33
useNativeAnimations:false works, not the best, other solutions?

**Comment by linxianxi** [comment] 2022-04-25 03:21
I used setTimeout 1000 to prevent it.
```
 useEffect(() => { 
  setTimeout(() => {
    PermissionsAndroid.request(...);
  }, 1000)
}, [])
```

**Closed** 2022-04-27 08:40 UTC
Labels: Platform: Android, Bug, Area: Drawer, BugBash 31.03
