### ISSUE TITLE
`onPress` of RectButton on Modal not effect in Android

### ISSUE THREAD

**Issue by luanle1106** [software-mansion/react-native-gesture-handler#996] opened 2020-03-03 08:45 UTC
`RectButton `  `onPress ` event is not fired when clicked.

See code below:

```typescript
import * as React from 'react';
import { StyleSheet, View, Switch, Alert, Modal } from 'react-native';
import { ClearButton, NormalTitle, OutlineButton } from './src';
import { gestureHandlerRootHOC, GestureHandlerRootView } from "react-native-gesture-handler";

const Hoc = gestureHandlerRootHOC(() => {
  return (
    <View accessible style={[{ flex: 1, alignContent: "center", alignItems: "center", justifyContent: "center", height: 500, width: 500 }]}>
      <ClearButton useRNComponent onPress={() => Alert.alert("Ok")} label="Click" />
      <OutlineButton onPress={() => Alert.alert("Ok")} label="Click" />
    </View>
  );
}, { width: 500, height: 500 });

export default function App() {
  return (
    <View style={styles.container}>
      <Modal visible>
        <Hoc />
      </Modal>
    </View>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'silver',
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    backgroundColor: "transparent",
    flex: 1,
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
  }
});

```

**Comment by brendan1809** [comment] 2020-03-03 14:58
check #139

**Comment by mydesweb** [comment] 2020-03-17 16:15
same problem with BorderlessButton , I checked #139 but there is no an easy fix.. hope will be fixed in RNGH soon.. on iOS everything is working out of the box

**Comment by Mandres07** [comment] 2020-06-13 00:43
Having the same problem here, the RectButton does not trigger the onPress when it is inside a Modal, but just for Android Devices, on iOS is perfect

**Comment by jakub-gonet** [comment] 2020-09-03 13:34
Duplicate of #139.

**Closed by jakub-gonet** 2020-09-03 13:34 UTC
