### ISSUE TITLE
xcode build failed

### ISSUE THREAD

**Issue by Staryixing** [software-mansion/react-native-gesture-handler#1298] opened 2021-01-07 02:08 UTC
Property 'allowedScrollTypesMask' not found on object of type 'RNBetterPanGestureRecognizer *'
Use of undeclared identifier 'UIScrollTypeMaskAll'

## Steps To Reproduce

1.npm install react-native-gesture-handler 
2. cd ios pod install

## Package versions

- React:16.9.0
- React Native:0.61.0
- React Native Gesture Handler:1.9.0

**Comment by jakub-gonet** [comment] 2021-01-07 07:14
Duplicate of #1235.

**Closed** 2021-01-07 07:14 UTC
