### ISSUE TITLE
Task :react-native-gesture-handler:compileDebugKotlin FAILED RN 0.69.3 with new arch

### ISSUE THREAD

**Issue by farell-flip** [software-mansion/react-native-gesture-handler#2168] opened 2022-08-12 08:46 UTC
### Description

When I build my app its failed with this errors:
```
Task :react-native-gesture-handler:compileDebugKotlin FAILED
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt: (28, 40): Unresolved reference: RNGestureHandlerButtonManagerDelegate
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt: (29, 40): Unresolved reference: RNGestureHandlerButtonManagerInterface
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt: (34, 80): Unresolved reference: RNGestureHandlerButtonManagerInterface
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt: (38, 19): Unresolved reference: RNGestureHandlerButtonManagerDelegate
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt: (47, 3): 'setForeground' overrides nothing
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt: (52, 3): 'setBorderless' overrides nothing
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt: (57, 3): 'setEnabled' overrides nothing
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt: (67, 3): 'setRippleColor' overrides nothing
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt: (72, 3): 'setRippleRadius' overrides nothing
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt: (77, 3): 'setExclusive' overrides nothing
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt: (82, 3): 'setTouchSoundDisabled' overrides nothing
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootViewManager.kt: (7, 40): Unresolved reference: RNGestureHandlerRootViewManagerDelegate
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootViewManager.kt: (8, 40): Unresolved reference: RNGestureHandlerRootViewManagerInterface
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootViewManager.kt: (17, 3): Unresolved reference: RNGestureHandlerRootViewManagerInterface
e: /Users/myname/Desktop/my-app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootViewManager.kt: (21, 17): Unresolved reference: RNGestureHandlerRootViewManagerDelegate
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
```

It works fine with new arch disabled, but failed when I enable it.

### Steps to reproduce

1. Enable new arch
2. Clean the project
3. Build the app (Android)

### Snack or a link to a repository

Not needed

### Gesture Handler version

2.5.0

### React Native version

0.69.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Acknowledgements

Yes

**Comment by JordyMota** [comment] 2022-08-12 19:45
+1

**Comment by CharlesPereira1** [comment] 2022-08-22 21:17
+2

**Comment by zhangfuchao** [comment] 2022-08-27 11:53
+4

**Comment by j-piasecki** [comment] 2022-08-29 10:02
It seems like codegen doesn't generate files for Gesture Handler. It would be grate if you could provide a repository with a reproduction or a more detailed list of steps to reproduce it.
When I tried clean & build on a new app after installing Gesture Handler and enabling the new architecture, it worked correctly for me.

**Comment by azizmobarak** [comment] 2022-08-29 15:20
+5 => 0.69.4

**Comment by bukhari-flip** [comment] 2022-08-30 03:42
After upgrade to new RN, I got the same issue. I need to clean up my `settings.gradle`, `build.gradle`, `app/build.gradle` following current version setup from RN repository to build succesfully.

I'm using:
```
react-native: "0.69.5" // (I try "0.69.4" and still works)
react-native-gesture-handler: "2.5.0"
```
and somehow i need to upgrade:
```
react-native-codegen: "^0.0.13"
```

I remove manual linking on `settings.gradle` since they already linked from `build/generated/rncli/../PackageList.java`

I also add `kotlinVersion` to `build.gradle` and remove `classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"` if any to avoid duplicate.
```
buildscript {
...
    ext {
        kotlinVersion = '1.6.10'
...
    }
}
...
```

For addition I found issue `Android.mk:Build command failed` and end up to fix [other issue](https://github.com/software-mansion/react-native-screens/issues/1483#issuecomment-1202331462) by setting `org.gradle.parallel=false` on `gradle.properties`.

**Comment by sgabriel** [comment] 2022-09-26 11:29
I'm getting the same error with 
Gesture Handler version
2.6.2

React Native version
0.70.1

**Comment by mohamed2m2018** [comment] 2022-09-27 19:11
I got the same error too

**Comment by j-piasecki** [comment] 2022-10-03 06:17
Have you tried the advice from @bukhari-flip? Mainly, updating `settings.gradle`, `build.gradle`, `app/build.gradle` to reflect the recent changes from the template and upgrading the `react-native-codegen`?

If it doesn't help, could you provide a link to a repository with an app that would allow to consistently reproduce it?

**Comment by androxxe** [comment] 2022-10-24 10:46
got this error too, any fix?

**Comment by azizmobarak** [comment] 2022-10-24 13:50
If the new arch is enabled I got the same issue on 0.64 , I see no fix on 70 too I guess

**Comment by Melber17** [comment] 2022-10-26 07:32
Yeah, the same issue.
react-native v0.69.5
react-native-gesture-handler v2.7.1

**Comment by zhangfuchao** [comment] 2022-10-26 07:51
I upgraded the kotlin version,fixed it。
Chinese translation into English, I hope you can understand

**Comment by nazrdogan** [comment] 2022-10-26 12:06
@zhangfuchao  which version are you using ?

**Comment by zhangfuchao** [comment] 2022-10-27 02:10
@nazrdogan 
kotlin_version:1.4.10
react-native-gesture-handler:2.6.0
react-native:0.64.2

**Comment by Melber17** [comment] 2022-11-03 11:47
> @nazrdogan kotlin_version:1.4.10 react-native-gesture-handler:2.6.0 react-native:0.64.2

the problem is related to the react native version

**Comment by dibyopra** [comment] 2022-11-08 09:42
+6

**Comment by codekojo** [comment] 2022-11-08 14:36
+7

**Comment by dibyopra** [comment] 2022-11-08 14:39
> +6
I changed my kotlin version to kotlinVersion = "1.5.31" in android/build.gradle
this fix my issues

**Comment by codekojo** [comment] 2022-11-08 15:00
So I solved it by 

1. changing `kotlinVersion = "1.4.10" to kotlinVersion = "1.5.20" in my android/build.gradle`
2. Also upgraded react native gesture  to` "react-native-gesture-handler": "^2.8.0"`,

**Comment by AndreiBehel** [comment] 2022-11-10 14:25
Same problem with android and enabled new architecture
kotlin_version: 1.6.10
react-native-gesture-handler: 2.8.0
react-native: 0.70.5

`e: /Users/andreibehel/Projects/mobile/node_modules/react-native-gesture-handler/android/reanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (5, 22): Unresolved reference: reanimated
e: /Users/andreibehel/Projects/mobile/node_modules/react-native-gesture-handler/android/reanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (8, 33): Unresolved reference: ReanimatedModule
e: /Users/andreibehel/Projects/mobile/node_modules/react-native-gesture-handler/android/reanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (12, 50): Not enough information to infer type variable T
e: /Users/andreibehel/Projects/mobile/node_modules/react-native-gesture-handler/android/reanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (12, 66): Unresolved reference: ReanimatedModule
e: /Users/andreibehel/Projects/mobile/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt: (18, 22): Unresolved reference: common
e: /Users/andreibehel/Projects/mobile/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt: (41, 45): Unresolved reference: GestureHandlerStateManager
e: /Users/andreibehel/Projects/mobile/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt: (432, 3): 'setGestureHandlerState' overrides nothing`

**Comment by AndreiBehel** [comment] 2022-11-11 10:49
Ok I've found that after adding reanimated 2.12 to the sample RN-0.70.5 project I got failing build

**Comment by AndreiBehel** [comment] 2022-11-11 14:05
`yarn add react-native-reanimated@next` solved my problem

**Comment by Melber17** [comment] 2022-11-12 07:02
The problem is in **react-native-gesture-handler** library. 

"react-native": "0.70.5",
"react-native-reanimated": "^3.0.0-rc.4",
 "react-native-gesture-handler": "^2.8.0",

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/63192915/201461862-79ddfa21-9ea4-4f11-a68e-17501b5e2eb4.png">

**Comment by AdhamMahmoud98** [comment] 2022-11-15 10:42
Fixed this issue by removing  kotlinVersion = '1.6.10' & classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:.6.10"

**Comment by JorgeArmandoMT** [comment] 2022-11-24 07:54
+7
I'm getting the same error with
Gesture Handler version: 2.2.1

React Native version: 0.68.2

**Comment by JorgeArmandoMT** [comment] 2022-11-25 06:15
> +7 I'm getting the same error with Gesture Handler version: 2.2.1
> 
> React Native version: 0.68.2

After trying different ways, you can finally fix it by updating to expo sdk 47 and expo dev-client 2.0.1.

also install 
expo-build-properties and add the following properties:

"compileSdkVersion": 33,
            "targetSdkVersion": 33,
            "buildToolsVersion": "30.0.2",
            "KotlinVersion": "1.7.10"

Good luck.

**Comment by Melber17** [comment] 2022-11-25 08:27
> > +7 I'm getting the same error with Gesture Handler version: 2.2.1
> > React Native version: 0.68.2
> 
> After trying different ways, you can finally fix it by updating to expo sdk 47 and expo dev-client 2.0.1 and update react-native-gesture-handler to 2.8.0 version.
> 
> also install expo-build-properties and add the following properties:
> 
> "compileSdkVersion": 33, "targetSdkVersion": 33, "buildToolsVersion": "30.0.2", "KotlinVersion": "1.7.10"
> 
> Good luck.

What about CLI?

**Comment by j-piasecki** [comment] 2022-11-28 07:28
Can you try changing [this line](https://github.com/software-mansion/react-native-gesture-handler/blob/main/android/build.gradle#L187) in Gesture Handler's `build.gradle` to
```groovy
srcDirs += ['src/fabric/java', 'build/generated/source/codegen/java']
```

**Comment by heroic** [comment] 2022-11-28 14:44
@j-piasecki this didn't work

> Can you try changing [this line](https://github.com/software-mansion/react-native-gesture-handler/blob/main/android/build.gradle#L187) in Gesture Handler's `build.gradle` to
> 
> ```groovy
> srcDirs += ['src/fabric/java', 'build/generated/source/codegen/java']
> ```

**Comment by heroic** [comment] 2022-11-29 12:17
for anyone looking for a repro, here are the steps:

- expo init. SDK 47
- yarn prebuild
- set `newArchEnabled=true` in `android/gradle.properties`
- install gesture handler and reanimated. versions: 2.8.0 and 2.12.0 respectively.
- yarn android

**Comment by heroic** [comment] 2022-11-29 13:26
repo here: https://github.com/heroic/gesture-handler-issue

**Comment by heroic** [comment] 2022-12-01 08:08
@j-piasecki any solution here?

**Comment by j-piasecki** [comment] 2022-12-01 13:48
@heroic Are you sure it's the same issue? In your repro it seems like Reanimated's package is not picked up during build, which persists after removing Gesture Handler. In this case I believe the GH build fails first because it picks up that Reanimated is in `node_modules` so it tries to include it, as some code is shared between the libraries, but fails because it cannot find it.

**Comment by heroic** [comment] 2022-12-01 14:03
Not sure, but the error log appears to be the same

**Comment by heroic** [comment] 2022-12-12 06:01
@j-piasecki were you able to check this? Any thing that you can share, that may help me check further into what to tinker?

**Comment by muhammeddeniz** [comment] 2022-12-23 11:03
this solved my problem
in `android/build.gradle`
```
 ext {
        kotlinVersion = "1.6.0"
        ...
}

 dependencies {
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0'
        ...
} 
```

**Comment by blueromans** [comment] 2023-01-18 21:18
+8
I'm getting the same error with
Gesture Handler version: 2.3.0

React Native version: 0.70.6

**Comment by gulsher7** [comment] 2023-01-23 13:24
+9
any solution ?

**Comment by savio777** [comment] 2023-02-01 20:03
> this solved my problem in `android/build.gradle`
> 
> ```
>  ext {
>         kotlinVersion = "1.6.0"
>         ...
> }
> 
>  dependencies {
>         classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0'
>         ...
> } 
> ```

with me it worked.

- package.json
```json
    "react": "18.2.0",
    "react-native": "0.71.1",
    "react-native-gesture-handler": "^2.9.0",
```

- android/build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        googlePlayServicesVersion = "17.0.0"

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"

        kotlinVersion = "1.6.0"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")

        classpath 'com.google.gms:google-services:4.3.14'

        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0'
    }
}
```

**Comment by buschco** [comment] 2023-02-27 10:03
> @heroic I believe it's caused by Reanimated 2.x.x which doesn't support fabric, on the new architecture you should be using Reanimated 3 (`3.0.0-rc.8` is the newest at the moment). [Here's](https://blog.swmansion.com/announcing-reanimated-3-16167428c5f7) more information about it.

So if I remove `react-native-reanimated` from my `package.json` it should work and if I want to have `react-native-reanimated` I have to use at least `3.0.0-rc.8`?

**Comment by j-piasecki** [comment] 2023-02-27 11:18
I cannot say whether your app will work after removing `react-native-reanimated` but if you're using the new architecture then you should be using the most recent release of Reanimated 3.

**Comment by nibaji** [comment] 2023-03-22 19:22
`react-native-reanimated: 3.0.2` is available with fabric support

**Comment by anthlasserre** [comment] 2023-05-14 20:52
Hey all 👋🏼 
Apparently, that was related to my SDK & Tools versions. I've upgraded from 32 to 33 and all was sorted.
```gradle
buildToolsVersion =
compileSdkVersion =
targetSdkVersion =
```

**Comment by alejodelosrios** [comment] 2023-05-16 16:36
Hi guys. 

React native : 0.71.8


For me what worked was:

1. android/app/build.gradle

`
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
`

3. android/build.gradle

`      ext {  
          kotlinVersion = '1.6.20'
          compileSdkVersion = 33 
       }

      dependencies {
         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
         classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlinVersion"
     }
`

3. android/settings.gradle

`
include ':react-native-gesture-handler'
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android')
`

**Comment by sureco-doug** [comment] 2023-05-17 20:51
> Hi guys.
> 
> React native : 0.71.8
> 
> For me what worked was:
> 
> 1. android/app/build.gradle
> 
> `apply plugin: 'kotlin-android' apply plugin: 'kotlin-android-extensions'`
> 
> 3. android/build.gradle
> 
> `ext { kotlinVersion = '1.6.20' compileSdkVersion = 33 }`
> 
> `dependencies { classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion" classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlinVersion" }`
> 
> 3. android/settings.gradle
> 
> `include ':react-native-gesture-handler' project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android')`

@alejodelosrios 's solution worked for me!

**Comment by atefwahab** [comment] 2023-05-18 08:49
> Hey all 👋🏼 Apparently, that was related to my SDK & Tools versions. I've upgraded from **32** to **33** and all was sorted.
> 
> ```groovy-gradle
> // android/build.gradle
> buildscript {
>   ext {
>     buildToolsVersion = 33
>     compileSdkVersion = 33
>     targetSdkVersion  '33.0.0'
>   }
> }
> ```

It worked for me to

**Comment by j-piasecki** [comment] 2023-05-18 09:29
I'll close the issue since it seems like you've found the solution.

**Closed by j-piasecki** 2023-05-18 09:29 UTC
Labels: Platform: Android, Missing repro

**Comment by chrisedington** [comment] 2023-05-23 08:28
> 

This worked for me

**Comment by chrisedington** [comment] 2023-05-23 08:28
> this solved my problem in `android/build.gradle`
> 
> ```
>  ext {
>         kotlinVersion = "1.6.0"
>         ...
> }
> 
>  dependencies {
>         classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0'
>         ...
> } 
> ```

This worked for me

**Comment by Muhiddin2007** [comment] 2023-05-31 11:56
> Hey all 👋🏼 Apparently, that was related to my SDK & Tools versions. I've upgraded from **32** to **33** and all was sorted.
> 
> ```groovy-gradle
> // android/build.gradle
> buildscript {
>   ext {
>     buildToolsVersion = 33
>     compileSdkVersion = 33
>     targetSdkVersion  '33.0.0'
>   }
> }
> ```

thanks, it work for me too

**Comment by kapilavaiya** [comment] 2023-06-15 14:22
// android/build.gradle - updating the version change worked for me
buildscript {
    ext {
 buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = '1.6.10'
 }       
}

**Comment by Pandit2903** [comment] 2023-06-22 16:37
//  in android/build.gradle
buildscript {
  ext {
    buildToolsVersion = 33
    compileSdkVersion = 33
    targetSdkVersion  '33.0.0'
  }
}

this work for me

**Comment by tyson90** [comment] 2023-07-14 12:07
In my case helped just update kotlin version in `android/build.gradle`:
```
buildscript {
    ext {
        kotlinVersion = "1.7.10"
        ...
```

**Comment by mibrahim2001** [comment] 2023-07-17 10:09
I solved it by upgrading my react-native-gesture-handler to version 2.9.0.

1.Update package.json:
Open your project's package.json file and find the dependency for react-native-gesture-handler. Change the version number to "2.9.0". It should look like this:
```
"dependencies": {
  "react-native-gesture-handler": "2.9.0",
  // other dependencies...
}
```

2.Uninstall node_modules folder.

3.npm install 

4.Try building your project now

**Comment by Gopal459** [comment] 2023-07-24 18:12
// android/build.gradle - updating the version change worked for me

buildscript {
    ext {
 buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = '1.6.10'
 }       
}

**Comment by ibilalchaudhary** [comment] 2025-06-18 11:25
Error message:
Execution failed for task ':react-native-gesture-handler:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

Root cause: Version incompatibility between React Native 0.73.0 and react-native-gesture-handler 2.14.0. React Native 0.73.x introduced new Android toolchain requirements (Android Gradle Plugin 8.1.x, Java 17, stricter Kotlin versions) that older gesture handler versions don't support.

Solution:
npm install react-native-gesture-handler@2.18.1
cd android && ./gradlew clean && cd ..
npx react-native run-android


IMPORTANT:: Remove ^ and ~ if there with 2.18.1 in package.json


Compatibility graph
react-native-gesture-handler 2.26.0+ → React Native 0.78.0+
react-native-gesture-handler 2.25.0+ → React Native 0.76.0+
react-native-gesture-handler 2.24.0+ → React Native 0.75.0+
react-native-gesture-handler 2.21.0+ → React Native 0.74.0+
react-native-gesture-handler 2.18.0+ → React Native 0.73.0+
react-native-gesture-handler 2.16.0+ → React Native 0.68.0+
react-native-gesture-handler 2.14.0+ → React Native 0.67.0+
react-native-gesture-handler 2.10.0+ → React Native 0.64.0+
react-native-gesture-handler 2.0.0+ → React Native 0.63.0+
