### ISSUE TITLE
Touchable don't work in Android. 1.7.0

### ISSUE THREAD

**Issue by Knjaz89** [software-mansion/react-native-gesture-handler#1152] opened 2020-07-31 09:52 UTC
`<TouchableOpacity
                                containerStyle={[
                                    Styles.stepContainer,
                                ]}
                                onPress={() => console.log('test')}
                            >
<Text> Press me</Text>
</TouchableOpacity>
`

**Comment by krakz999** [comment] 2020-08-07 19:27
Same issue

**Comment by jakub-gonet** [comment] 2020-08-11 15:21
Duplicate of #578.

**Closed by jakub-gonet** 2020-08-11 15:21 UTC
