### ISSUE TITLE
Swipe back doesnt take 100% of screen width

### ISSUE THREAD

**Issue by moak** [software-mansion/react-native-gesture-handler#1435] opened 2021-04-20 19:18 UTC
## Description
The gesture handle only takes a small width when swiping to go back. I would like to discuss about it because it does not seem to be configurable

### Screenshots
![image](https://user-images.githubusercontent.com/552623/115451178-27c67180-a21d-11eb-8e58-6a5ffb351baa.png)

### Expected behavior
- The swipe back `width` should be adjustable in order to swipe back on the entire screen 

### Actual behavior
- The swipe back only works on a small width percentage of the screen (as showed above)

## Package versions
- React: 16.13.1
- React Native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz
- React Native Gesture Handler: ~1.8.0

**Comment by jakub-gonet** [comment] 2021-08-23 04:32
I'm not sure if I follow.
Could you please attach the code you used in your component and describe how you use RNGH in this scenario?

This may be a duplicate of #833 so I'm closing it preemptively.

**Closed by jakub-gonet** 2021-08-23 04:32 UTC
