### ISSUE TITLE
IllegalArgumentException - Scroll View - Expo

### ISSUE THREAD

**Issue by abudhia-oyo** [software-mansion/react-native-gesture-handler#1205] opened 2020-10-07 22:22 UTC
## Description
On tapping multiple times randomly with multiple fingers on a Scroll View, the app crashes. This is inside an expo project.

### Screenshots
Video attached
https://drive.google.com/file/d/1C9f5ACMEPlYF1Crh2PkBt_Y7Q9MQL9kK/view?usp=drivesdk

## Steps To Reproduce
1. Android App from https://play.google.com/store/apps/details?id=com.herokuapp.tambolah
2. Go to any of the Scroll Views and try to randomly tap as shown in the video

### Expected behavior
App shouldn't crash.
### Actual behavior
```
java.lang.IllegalArgumentException: 
  at android.view.MotionEvent.nativeGetAxisValue (MotionEvent.java)
  at android.view.MotionEvent.getY (MotionEvent.java:2216)
  at android.widget.ScrollView.onTouchEvent (ScrollView.java:760)
  at com.facebook.react.views.scroll.ReactScrollView.onTouchEvent (ReactScrollView.java:299)
  at android.view.View.dispatchTouchEvent (View.java:11864)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3043)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2679)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at versioned.host.exp.exponent.modules.api.components.gesturehandler.react.RNGestureHandlerEnabledRootView.dispatchTouchEvent (RNGestureHandlerEnabledRootView.java:39)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3049)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2693)
  at com.android.internal.policy.DecorView.superDispatchTouchEvent (DecorView.java:592)
  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent (PhoneWindow.java:1980)
  at android.app.Activity.dispatchTouchEvent (Activity.java:3380)
  at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:69)
  at com.android.internal.policy.DecorView.dispatchTouchEvent (DecorView.java:548)
  at android.view.View.dispatchPointerEvent (View.java:12123)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:5122)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:4913)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4407)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4477)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4435)
  at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4577)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4443)
  at android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:4634)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4407)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4477)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4435)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4443)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4407)
  at android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:7073)
  at android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:7047)
  at android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:6998)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:7198)
  at android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:195)
  at android.os.MessageQueue.nativePollOnce (MessageQueue.java)
  at android.os.MessageQueue.next (MessageQueue.java:329)
  at android.os.Looper.loop (Looper.java:150)
  at android.app.ActivityThread.main (ActivityThread.java:6748)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:556)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:875)
```

## Snack or minimal code example
TBD

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Gesture Handler: ~1.7.0

**Comment by abudhia-oyo** [comment] 2020-10-09 05:40
@jakub-gonet I'm on the latest expo SDK 39, managed workflow. Why would the issue still exist if this was closed?

**Comment by jakub-gonet** [comment] 2020-10-09 10:41
Probably we thought it was resolved when in reality it wasn't. 

I investigated it a bit and this is triggered by `super.dispatchTouchEvent(ev)` in `dispatchTouchEvent(MotionEvent ev)`. It's Android method which calls [`MotionEvent.getY`](https://android.googlesource.com/platform/frameworks/base/+/6a839703cd9aa72f5c6f107d0a8f894601d5c308/core/java/android/view/MotionEvent.java#1479) which calls native method [`nativeGetAxisValue`](https://android.googlesource.com/platform/frameworks/base/+/6a839703cd9aa72f5c6f107d0a8f894601d5c308/core/jni/android_view_MotionEvent.cpp#542). It contains [check for pointer index](https://android.googlesource.com/platform/frameworks/base/+/6a839703cd9aa72f5c6f107d0a8f894601d5c308/core/jni/android_view_MotionEvent.cpp#150) which crashes here.

A similar problem was submitted as [Android bug report](https://issuetracker.google.com/issues/36931456).

Could you provide your android version and more importantly, reproduction example?

**Comment by abudhia-oyo** [comment] 2020-10-09 13:09
Please check the Google drive video link. I have shared the app link as well. It happens on almost all the Android versions and phones.

More than 95% of the native crashes on my production app is related to the react-native-gesture-handler and happens with 5% of the sessions(95% of the sessions are crash free).

If you could really solve it, that would be a great relief. Google reports these many crashes as a bad behavior.

Attaching some reports from the play console on Android version split.

![Screenshot_20201009-183838](https://user-images.githubusercontent.com/40752377/95586748-bda76580-0a5e-11eb-92bc-9eb49cceafc7.jpg)
![Screenshot_20201009-183828](https://user-images.githubusercontent.com/40752377/95586758-c009bf80-0a5e-11eb-9da5-658ac448d548.jpg)

**Comment by jakub-gonet** [comment] 2020-10-09 13:15
Makes sense but it's really hard to debug it basing only on stack traces so I really need some repro example, where I can test it locally and reliably crash the app. 

Could you extract this component from your app and simplify it up to the point where it only uses react-native / react-native-gesture-handler stuff and still crashes? Ideally, it'd be 30-40 lines snippet which I can paste and run.

**Comment by jakub-gonet** [comment] 2020-10-09 13:21
Besides that, try updating RNGH to 1.8.0, we fixed some threading issues so it may fix your issue.

**Comment by abudhia-oyo** [comment] 2020-10-09 13:30
I did try manually bumping the RNGH version on my managed expo app, however was still able to repro this issue on the updated build.

We did put a try catch around the IllegalArgumentException, right? Shouldn't that atleast prevent the crash?

**Comment by abudhia-oyo** [comment] 2020-10-09 14:13
Okay. Reproducing this issue has been very tricky as we only get to know about it from the Play Console crash reports when thousands of users out there use the app. Otherwise haven't really been able to isolate this ourselves. There's no reason a real user would tap with multiple fingers rapidly on their screens.

Though tricky, i'll take a few attempts and see if can come up with a baremin snack. Meanwhile if there's any other way you could help that'll be great.

**Comment by abudhia-oyo** [comment] 2020-10-09 17:44
@jakub-gonet can you confirm if patch-package can we used with expo managed workflow?

**Comment by jakub-gonet** [comment] 2020-10-09 18:09
I'm afraid you have to eject in order to apply patches. Expo keeps their internal, slightly modified versions of libraries. A good way to do that is to eject project and after fix will be added to expo you can revert commit that contains changes from ejection.

**Comment by abudhia-oyo** [comment] 2020-10-09 20:03
Alrighty. One last question, if I don't need to make use of any of the gesture on my ScrollView or Touchable opacity, should it be of any help if it's imported directly from react-native and RNGH is not used at all?

Meanwhile also I'm trying to narrow down the repro steps. It seems to particularly crash when doing pinch zoom with multiple fingers.

**Comment by todorone** [comment] 2020-12-31 02:50
I can confirm that the issue is still relevant on the latest version of `react-native-gesture-handler`.
And yes, this bug belongs to category that is next to impossible to consistently reproduce, but still it's need to be resolved.

@jakub-gonet Can we merge this PR? It is not harm to add `try/catch` afaik:
https://github.com/software-mansion/react-native-gesture-handler/pull/522

<img width="1066" alt="Screenshot 2020-12-31 at 04 40 43" src="https://user-images.githubusercontent.com/423701/103391672-4a743380-4b23-11eb-8b51-c8d2919200dc.png">

**Comment by jakub-gonet** [comment] 2020-12-31 13:04
I'm hesitant to merge that kind of hack. This situation shouldn't happen and it's a bug either in Android implementation, or, more likely bug in RNGH or Expo integration with RNGH.
Wrapping it in the try-catch is harmful because now you don't fail immediately there's something wrong but you carry on with possibly wrong values. Patching this one will prevent folks from submitting issues with this particular stack trace and consequently make fixing the crash impossible. Having stack trace helps us categorize bugs and it's easier to fix than fixing an issue like "this particular example behaves in not expected way every now and then".

Submitting any reproduction example and/or describing what do you have to do to trigger this exception will really help us resolve this.

**Comment by todorone** [comment] 2020-12-31 13:41
> This situation shouldn't happen and it's a bug either in Android implementation, or, more likely bug in RNGH or Expo integration with RNGH.

This is definitely not Expo integration with RNGH bug as we use RNGH independently of expo libraries. As i mentioned before there is not much info i may add to previous reports, it's definitely happens with `FlatList` imported from RNGH, in my case it's inverted.

> Wrapping it in the try-catch is harmful because now you don't fail immediately there's something wrong but you carry on with possibly wrong values. Patching this one will prevent folks from submitting issues with this particular stack trace and consequently make fixing the crash impossible. Having stack trace helps us categorize bugs and it's easier to fix than fixing an issue like "this particular example behaves in not expected way every now and then".

I totally agree that swallowing exceptions is not good idea at all. But at the same time in this case according to bug report You pointed [out](https://issuetracker.google.com/issues/36931456), it's more likely an Android API issue which occurs very rarely, but still it's a bit annoying to have crashes(even very rare) for no reason so maybe in this case just wrapping it in `try/catch` is not so bad idea. Anyway, it's up to You to decide. But while even so huge Android community didn't find out consistently reproducing code sample, it's unlikely to await it from brave but sparse RN folks...😼 

@jakub-gonet

**Comment by gogul-ct** [comment] 2021-04-27 08:32
@jakub-gonet  This issue can be reproduced by Tapping the ScrollView with Multiple Fingers and trying to scroll the content. This issue is happening for me with RNGH 1.9.0.

**Comment by Prernabudh** [comment] 2021-06-07 06:46
Is there any solution to this crash? I have faced the same crash on my app. @jakub-gonet @abudhia-oyo

**Comment by gdoudeng** [comment] 2021-07-19 02:41
+1

**Comment by jakub-gonet** [comment] 2021-08-16 07:04
@gogul-ct I couldn't reproduce it that way, could you share your repro?

https://user-images.githubusercontent.com/12465392/129524127-f2e243ae-2075-46cf-9042-46b8abe14351.mov

```jsx
import * as React from 'react';
import { SafeAreaView, View } from 'react-native';
import { ScrollView } from 'react-native-gesture-handler';

export default () => {
  return (
    <SafeAreaView style={styles.container}>
      <ScrollView>
        {Array.from(Array(30)).map((_, i) => (
          <View key={i} style={styles.rectangle} />
        ))}
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = {
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 20,
  },
  rectangle: {
    width: 200,
    height: 200,
    backgroundColor: 'seagreen',
    marginBottom: 20,
  },
};
```

**Comment by jakub-gonet** [comment] 2021-08-16 07:34
I'll close this one since it's not really actionable for us. We don't edit MotionEvents in RNGH and only create them in three places. [One place](https://github.com/software-mansion/react-native-gesture-handler/blob/a5d6251830b0540dddfbc8470daf9b611c5cbcea/android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandler.kt#L223-L224) may have a bug in logic, I'll add additional checks for that.

If you're able to repro this consistently, please reply with the **reproduction example** or create a new issue.

**Closed by jakub-gonet** 2021-08-16 07:34 UTC
Labels: Missing info, Platform: Android
