### ISSUE TITLE
[Android TouchableOpacity] onPress not working on android (RN 0.62.2)

### ISSUE THREAD

**Issue by RickameCua** [software-mansion/react-native-gesture-handler#1198] opened 2020-09-24 10:55 UTC
Trying to use the TouchableOpacity of react-native-gesture-handler to avoid triggering onPress while scrolling/changing tabs to a ScrollView/Flatlist because the TouchableOpacity on react-native triggers onPress while scrolling/changing tabs.

All I did was replace
`import { TouchableOpacity } from 'react-native';`
to
`import { TouchableOpacity } from 'react-native-gesture-handler';`
and the onPress event is not working anymore.
I used react-native-gesture-handler version 1.6.1 at first and ugraded to 1.8.0 still not working.

Anyone got any tips for this problem?

**Comment by jakub-gonet** [comment] 2020-09-24 11:16
Duplicate of #578.

**Closed by jakub-gonet** 2020-09-24 11:16 UTC
