### ISSUE TITLE
TouchableOpacity is working in Android?

### ISSUE THREAD

**Issue by akiradeveloper** [software-mansion/react-native-gesture-handler#578] opened 2019-04-24 08:32 UTC
I am using RN 0.59.5 with this library and it seems that TouchableOpacity doesn't handle onPress hook in Android whereas it does in iOS. Is this a known issue?

**Comment by adamczyk777** [comment] 2019-04-30 10:00
Hi @akiradeveloper I bumped version of React Native in Example app to 0.59.5 and TouchableOpacity on android records onPress events. You can check this out by yourself on this branch up until it gets merged to master 😊

https://github.com/kmagiera/react-native-gesture-handler/tree/upgrade-react-native

**Comment by PierreCapo** [comment] 2019-06-01 01:55
Hello,

I have the same issue right now with `react-native` 0.59.8 and `react-native-gesture-handler` 1.2.2
TouchableOpacity and TouchableHighlight aren't working on a basic react-native app on Android (it works well on iOS)
I have changed the import to use the touchables from the `react-native` library and it works

**Comment by kissthedevel** [comment] 2019-08-19 14:15
I have the same problem.. but in react native version 0.60.x TouchableOpacity of react-native library seems to work well.

**Comment by CyxouD** [comment] 2019-11-26 12:07
To not make mistake described by @PierreCapo again, added `ESLint` rule to show error when using buttons from `react-native-gesture-handler`:
```
"no-restricted-imports": [
      "error",
      {
        "paths": [
          {
            "name": "react-native-gesture-handler",
            "importNames": [
              "TouchableOpacity",
              "TouchableNativeFeedback",
              "TouchableHighlight",
              "TouchableWithoutFeedback"
            ],
            "message": "Please import it from 'react-native' instead."
          }
        ]
      }
    ]
```

**Comment by zingerj** [comment] 2020-01-30 07:36
Not able to get `react-native-gesture-handler` Touchables working at all (trying on iOS simulator) on `react-native@0.61.5`. Any update on this? Using the default Touchables from `react-native` for now...

**Comment by neiker** [comment] 2020-01-31 13:23
This is what I do, which is really ugly:

```tsx
// eslint-disable-next-line no-restricted-imports
import {
  TouchableOpacity as TouchableOpacityRN,
  TouchableNativeFeedback as TouchableNativeFeedbackRN,
  TouchableHighlight as TouchableHighlightRN,
  TouchableWithoutFeedback as TouchableWithoutFeedbackRN,
  FlatList as FlatListRN,
  ScrollView as ScrollViewRN,
  Platform,
} from 'react-native';

// eslint-disable-next-line no-restricted-imports
import {
  TouchableOpacity as TouchableOpacityRNGH,
  TouchableNativeFeedback as TouchableNativeFeedbackRNGH,
  TouchableHighlight as TouchableHighlightRNGH,
  TouchableWithoutFeedback as TouchableWithoutFeedbackRNGH,
  FlatList as FlatListRNGH,
  ScrollView as ScrollViewRNGH,
} from 'react-native-gesture-handler';

const isIOS = Platform.OS === 'ios';

export type TouchableOpacity = TouchableOpacityRN;
export const TouchableOpacity = isIOS
  ? TouchableOpacityRNGH
  : TouchableOpacityRN;

export type TouchableNativeFeedback = TouchableNativeFeedbackRN;
export const TouchableNativeFeedback = isIOS
  ? TouchableNativeFeedbackRNGH
  : TouchableNativeFeedbackRN;

export type TouchableHighlight = TouchableHighlightRN;
export const TouchableHighlight = isIOS
  ? TouchableHighlightRNGH
  : TouchableHighlightRN;

export type TouchableWithoutFeedback = TouchableWithoutFeedbackRN;
export const TouchableWithoutFeedback = isIOS
  ? TouchableWithoutFeedbackRNGH
  : TouchableWithoutFeedbackRN;

export type FlatList<T> = FlatListRN<T>;
export const FlatList: typeof FlatListRN = isIOS
  ? (FlatListRNGH as typeof FlatListRN)
  : FlatListRN;

export type ScrollView = ScrollViewRN;
export const ScrollView: typeof ScrollViewRN = isIOS
  ? (ScrollViewRNGH as typeof ScrollViewRN)
  : ScrollViewRN;
```

**Comment by noway** [comment] 2020-03-15 22:49
What if I want to use TouchableNativeFeedback from `react-native-gesture-handler`? It has a WAY BETTER ripple effect, literally day and night in terms of ripple animation.

**Comment by noway** [comment] 2020-03-15 23:28
this helped me: https://github.com/software-mansion/react-native-gesture-handler/issues/699

**Comment by YahiaBadr** [comment] 2020-04-12 11:14
@noway did you find any solution? i looked at the link you provided but unfortunately, my project is an expo manged one. So if you got any other solution please let me know.

**Comment by noway** [comment] 2020-04-12 22:44
expo doesn't provide as much flexility as standard react native installation for issues exactly like this, so i'd recommend not to use it.

**Comment by mauroduq** [comment] 2020-07-04 17:14
I get back...  
I use this
import {TouchableOpacity} from 'react-native';

Instead 
import {TouchableOpacity} from 'react-native-gesture-handler';

For some reason, The first one works as well on IOS but not on Android

**Comment by ChenhuaWANG22** [comment] 2020-08-14 07:24
for someone has to use touchables from react-native-gesture-handler for iOS:

let TouchableHighlight,TouchableOpacity;
if (Platform.OS === 'ios') {
    ({ TouchableHighlight,TouchableOpacity } = require('react-native-gesture-handler'));
} else {
    ({ TouchableHighlight,TouchableOpacity } = require('react-native'));
}

**Comment by jakub-gonet** [comment] 2020-08-25 13:35
I wasn't able to repro that, TouchableOpacity is _kinda_ working on android (doesn't have opacity though). Used code from the master branch.

Could you guys please share some small reproduction example with RNGH version, so I can test and fix that?

Example code:
```jsx
import React from 'react';
import { SafeAreaView, Text, Platform } from 'react-native';
import { TouchableOpacity } from 'react-native-gesture-handler';

export default () => {
  return (
    <SafeAreaView style={styles.container}>
      <TouchableOpacity
        style={[styles.rectangle]}
        onPress={() => console.log('Touch', Platform.OS)}>
        <Text>Press me!</Text>
      </TouchableOpacity>
    </SafeAreaView>
  );
};

const styles = {
  container: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  rectangle: {
    backgroundColor: 'pink',
    width: 100,
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
};

```

![Screen Recording 2020-08-25 at 15 30 12](https://user-images.githubusercontent.com/12465392/91180577-2bcedd80-e6e8-11ea-9048-a5f71b8ced5e.gif)

**Comment by tandat2209** [comment] 2020-08-29 13:57
@jakub-gonet  Seems like it does not work inside a Modal

Please take a look at this snack

https://snack.expo.io/@dattannguyen/touchableopacity-does-not-work-on-android

**Comment by jakub-gonet** [comment] 2020-08-29 14:09
@tandat2209, this may be related to #139.

**Comment by bluenex** [comment] 2020-09-07 16:31
I confirm `Touchableopacity` doesn't have opacity when it is being tapped. I am upgrading RN version to the latest (0.63.2) and having RNGH 1.7.0 as a dependency of React-Navigation. 

I used `TouchableOpacity` imported from `react-native` before and just change to import from RNGH after upgrading RN version as the one from RN doesn't have opacity on both iOS and Android. However, the one imported from RNGH only works properly on iOS. It doesn't change opacity on click on Android.

It is not on Modal either. In my case, I found it on [storybook](https://github.com/storybookjs/react-native) (image below).

![image](https://user-images.githubusercontent.com/11027706/92406385-133bda00-f162-11ea-8b9a-86fcaa3012d9.png)

(`justify-content` seems to have weird behavior after upgrading as well 😅 )

**Comment by jakub-gonet** [comment] 2020-09-07 17:02
@bluenex, could you provide some small example of code?

**Comment by bluenex** [comment] 2020-09-08 04:09
> @bluenex, could you provide some small example of code?

Here it is:

```js
import { TouchableOpacity } from 'react-native-gesture-handler';
import styled from styled-components;

const ButtonContainer = styled(TouchableOpacity)`...`;

const StyledView = styled.View`...`;

const Button = ({ children, ...buttonProps }) => (
  <ButtonContainer {...buttonProps}>
    <StyledView>
      <Text>
        { children }
      </Text>
    </StyledView>
  <ButtonContainer>
);
```

So this is my custom button component which is styled using `styled-components`. This button is working perfectly on iOS but not Android. 

More information, I use `react-navigation` and follow it docs here https://reactnavigation.org/docs/getting-started/. One thing I'm very curious is that it doesn't suggest to add anything to either `MainActivity.java` or `MainApplication.java`, just `import 'react-native-gesture-handler';` in entry file. Is that enough?

**Comment by SUMITIOS** [comment] 2020-09-23 14:06
> Hello,
> 
> I have the same issue right now with `react-native` 0.59.8 and `react-native-gesture-handler` 1.2.2
> TouchableOpacity and TouchableHighlight from react-native-gesture-handler aren't working on a basic react-native app on Android (it works well on iOS).
> 
> I have changed the import to use the touchables from the `react-native` library and it works

It's not working in React native 0.62.2, 0.63.x and react-native-gesture-handler "^1.8.0" too. In fact in most versions of RN  the problem is there. The onPress does not work at all. One must import it from "react-native" always for android

**Comment by flexbox** [comment] 2020-10-29 13:29
Confirmed as well on the last version of the expo SDK
```
"react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
"react-native-gesture-handler": "~1.7.0",
```

**Comment by anastasiia-tripuz** [comment] 2021-07-03 02:29
> I moved the child component to be a sibling of the touchable component and then gave it absolute positioning such that it draws over the child. It's a stupid hack but suits my use case.
> 
> ```js
> <View>
>     <TextInput
>        //editable={false}
>       />
>      <TouchableOpacity 
>          style={{position: 'absolute', left:0, top:0 ,width:'100%', height: '100%'}} 
>           onPress={()=>{setIsModalVisible(true)}}>
>      </TouchableOpacity>
> </View>
> ```

If you want to use `TouchableOpacity` from the `react-native-gesture-handler` and use **`position: "absolute"`** you should provide **`containerStyle`** props instead of the `style`. 

```
import { TouchableOpacity } from 'react-native-gesture-handler';

...

<TouchableOpacity 
    onPress={() => {}} 
    containerStyle={{ 
        position: 'absolute',
        top: 0,
        left: 0
    }}
>
   <Text>Press</Text>
</TouchableOpacity>
```

**Comment by jakub-gonet** [comment] 2021-08-15 18:22
I submitted PR fixing opacity effect but I wasn't able to repro this issue. If you still experience it, make sure you set up RNGH correctly and provide a working repro example.

**Closed by jakub-gonet** 2021-08-15 18:22 UTC
Labels: Missing info, Platform: Android, Platform: Cross platform inconsistency, To verify
