### ISSUE TITLE
Basebutton not work on react-naitve-modal

### ISSUE THREAD

**Issue by KoreanThinker** [software-mansion/react-native-gesture-handler#1033] opened 2020-04-13 06:32 UTC
```js
import Modal from 'react-native-modal';
import { BaseButton } from 'react-native-gesture-handler';

<Modal>
    <BaseButton onPress={someFunction} />
</Modal>
```
this code not work 
```js
import Modal from 'react-native-modal';
import { BaseButton } from 'react-native-gesture-handler';
import { TouchableWithoutFeedback } from 'react-native' // this code cumbersome

<Modal>
    <TouchableWithoutFeedback onPress={someFunction} >  // this code too
        <BaseButton  />
    </TouchableWithoutFeedback>
</Modal>
```
so I wrapping "TouchableWithoutFeedBack"

**Comment by ViniCleFer** [comment] 2020-05-18 14:54
RectButton also didn't work in react-native-modal.

**Comment by Mandres07** [comment] 2020-06-13 00:42
Having the same problem here, the RectButton does not trigger the onPress when it is inside a Modal, but just for Android Devices, on iOS is perfect

**Comment by jakub-gonet** [comment] 2020-08-27 15:56
Duplicate of #139.

**Closed by jakub-gonet** 2020-08-27 15:56 UTC
