### ISSUE TITLE
RCTBridge required dispatch_sync to load RNGestureHandlerModule

### ISSUE THREAD

**Issue by billnbell** [software-mansion/react-native-gesture-handler#1825] opened 2022-01-14 04:02 UTC
Latest version. Not sure why I am getting this.

RCTBridge required dispatch_sync to load RNGestureHandlerModule

**Comment by vanenshi** [comment] 2022-01-14 07:47
Same Here

**Comment by j-piasecki** [comment] 2022-01-14 11:42
Hi! This issue is a duplicate of https://github.com/software-mansion/react-native-gesture-handler/issues/1770. I'll close this one in order to keep the discussion in one place.

**Closed by j-piasecki** 2022-01-14 11:42 UTC
