### ISSUE TITLE
Animated gesture must be callback worklet

### ISSUE THREAD

**Issue by vemarav** [software-mansion/react-native-gesture-handler#1758] opened 2021-12-13 18:11 UTC
```
Gesture.Tap().onStart(() => console.log('tapped'))
```

react-native: 0.66.4
react-native-gesture-handler: 2.1.0
react-native-reanimated: 2.3.0

**Comment by j-piasecki** [comment] 2021-12-15 07:41
Hi, could you share some more code that is causing this issue? I tested the snipped you have provided and it works for me.

Callbacks passed to the gestures should be workletized automatically, but if it fails for some reason you can try to add `'worklet'` directive as the first line of the function.

**Comment by vemarav** [comment] 2021-12-15 15:57
@j-piasecki  have you tried on above mentioned version combination. using 2.0.0 works as expected.

**Comment by j-piasecki** [comment] 2021-12-16 07:38
Yes, I have tried the exact version combination of React Native, Reanimated and Gesture Handler that you described, and it works on a clean project.

**Comment by vemarav** [comment] 2021-12-16 11:26
my worklet involves `setSwipe` state function, may be that's why?

**Comment by j-piasecki** [comment] 2021-12-17 08:13
Yes, you should wrap function calls with `runOnJS` in worklets, however I can't definitely say that it's the reason for this problem without the reproduction.

**Comment by wcandillon** [comment] 2022-01-11 15:10
I've been experiencing this error message with expo 44. Everything was working fine but as soon as I started to use Pinch() with onEnd(), I needed to mark all callbacks as "worklet". Could it be because of the code formatting the babel plugin is not able anymore to whitelist the callbacks?

**Comment by LeviWilliams** [comment] 2022-01-26 21:32
Experiencing this as well with a gesture detector with a tap and long press. Note this code all worked totally fine until I added reanimated to the project.
React native 0..66.4
Rngh 2.2.0
Reanimated 2.3.1

```
  const longPressHandler = Gesture.LongPress()
    .onStart((event) => {
        onLongPress(event);
    })
    .onEnd((event) => {
      ) 
        onPressOut(event);
    });

  const tapHandler = Gesture.Tap()
    .onStart((event) => {
        onTap(event);
    })
    .onEnd((event) => {
        onTapOut(event);
    });

  const composed = Gesture.Exclusive(longPressHandler, tapHandler);

  return <GestureDetector gesture={composed}>{children}</GestureDetector>;
```

**Comment by WoLewicki** [comment] 2022-03-31 12:35
Since there is already an issue for what @wcandillon reported: https://github.com/software-mansion/react-native-gesture-handler/issues/1821, I will close this issue then. Feel free to comment if I am wrong and we can always reopen it.

**Closed by WoLewicki** 2022-03-31 12:35 UTC
