### ISSUE TITLE
dont recognize gesture event map view (react-native-maps) Android

### ISSUE THREAD

**Issue by windhelm** [software-mansion/react-native-gesture-handler#857] opened 2019-12-02 19:37 UTC
On ios work fine.

```
<TapGestureHandler
                    onHandlerStateChange={this._onSingleTap}
                    waitFor={this.doubleTapRef}>
                    <TapGestureHandler
                        ref={this.doubleTapRef}
                        onHandlerStateChange={this._onDoubleTap}
                        numberOfTaps={2}>
                        <Animated.View style={{position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 1, backgroundColor: 'red'}}>
                    {this.state.didFinishInitialAnimation && <PinchGestureHandler
                        ref={this.pinchRef}
                        onGestureEvent={this._onPinchGestureEvent}
                        onHandlerStateChange={this._onPinchHandlerStateChange}>
                            {this.props.geo && <MapView.Animated
                                                                      style={{position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 0}}
                                                                      ref={(mapView) => {this.mapView = mapView}}
                                                                      provider={PROVIDER_GOOGLE}
                                                                      mapPadding={{
                                                                        top: 0,
                                                                        right: 0,
                                                                        bottom: 0,
                                                                        left: 0
                                                                      }}
                                                                      scrollEnabled={this.zoomed ? false : true}
                                                                      showsIndoorLevelPicker={false}
                                                                      pitchEnabled={false}
                                                                      rotateEnabled={false}
                                                                      zoomEnabled={false}
                                                                      zoomControlEnabled={false}
                                                                      toolbarEnabled={false}
                                                                      camera={this.camera}
                                                                      onMapReady={() => this.mapReady()}
                                                                      onPanDrag={() => this.onPanDragHandle()}
                                                                      onRegionChangeComplete={(region) => this.onRegionChangeCompleteHandle(region)}
                                                                      customMapStyle={mapStyle}>
                        <CustomMarker color={'#540D85'} active={true} lat={this.props.geo.coord.lat} long={this.props.geo.coord.long}/>
                    </MapView.Animated>}</PinchGestureHandler>}
```
Without MapView work fine just simple <View/>
Please help me, thanks!

**Comment by jmkmay** [comment] 2020-06-01 14:49
@windhelm did you ever figure this out? Ran into the same issue for an app I'm building and wondering if you have any input.

**Comment by jakub-gonet** [comment] 2020-09-03 18:16
This issue was not active for some time so I'm closing it. It may be a duplicate of #465.
If you need further help please reply.

**Closed by jakub-gonet** 2020-09-03 18:16 UTC
Labels: Gesture handlers

**Comment by mrousavy** [comment] 2021-01-19 10:13
@jakub-gonet maybe not directly related to the issue, but I'm having problems with using a `<PanGestureHandler>` over a map.

The idea is to provide the Snapchat look and feel, where you have horizontal views in which you can swipe between. One of the views is a map, which obviously also has a pan gesture handler to enable panning on the map.

Now I'm trying to define an "area of activation", aka I want the horizontal view `<PanGesturerHandler>` to only activate if it has been started from the edge of the screen, otherwise ignore the gesture and let the map's pan gesture handler handle it.

Is this possible with RNGH, or do I have to tweak the native map gesture handlers?
