### ISSUE TITLE
Property 'allowedScrollTypesMask' not found on object of type 'RNBetterPanGestureRecognizer *'

### ISSUE THREAD

**Issue by joseroberto-toko** [software-mansion/react-native-gesture-handler#1279] opened 2020-12-15 20:34 UTC
I comment this line and its works for me 

node_modules/react-native-gesture-handler/ios/Handlers/RNPanHandler.mnode_modules/react-native-gesture-handler/ios/Handlers/RNPanHandler.m

line: **209 to 214**

![image](https://user-images.githubusercontent.com/4127445/102269617-a8860180-3efb-11eb-928d-b37feb54f31d.png)

react-native-gesture-handler: 1.9.0
MacOs Catalina: 10.15.7
react-native: 0.60.4
react-native-cli: 2.0.1

**Comment by andersoncscz** [comment] 2020-12-15 21:22
I'm having the same issue:

MacOs Big Sur: 11.0.1
XCode: 11.4 beta
Simulator: IPhone 11 - IOS 13.4

react-native-gesture-handler 1.9.0
react-native: 0.63.2
react-native-cli: 2.0.1

I downgraded to 1.7.0 (the previous version I was using before updated it) and it built successful again.

**Comment by jakub-gonet** [comment] 2020-12-15 23:19
Duplicate of #1235.

Upgrade your Xcode version.

**Closed by jakub-gonet** 2020-12-15 23:19 UTC
