### ISSUE TITLE
Weird behaviour happens when scale, translateX, translateY, rotate mixed up to use

### ISSUE THREAD

**Issue by tikkichan4** [software-mansion/react-native-gesture-handler#229] opened 2018-06-28 07:16 UTC
Demo: 
[https://snack.expo.io/Hy3eq-fGQ](https://snack.expo.io/Hy3eq-fGQ)

When the image is scaling larger, the movement speed will be very slow which is not same as the speed before scaling.

This problem also happens when rotating the image to -180 degrees. When i drag the image to going up, it will actually goes down.

i have using a tons of days for solving this problem but it is not worked.
Any workaround for this use case ? Thanks a lot

**Comment by Temzasse** [comment] 2018-07-03 14:08
I'm having a similar issue where the dragging speed is affected by the scaling factor if the element.

So, if I scale the element when the pan starts like this:
```
Animated.spring(this.scale, {
    friction: 3,
    toValue: SCALING_FACTOR,
    useNativeDriver: true,
}).start();
```
The movement speed seems to be `1 / SCALING_FACTOR * speed`.

I can fix the end result when the user ends the pan gesture by having `translationX/Y * SCALING_FACTOR` in **onHandlerStateChange** but this does not help with the slowness during the pan gesture.

**Comment by adamgrzybowski** [comment] 2020-07-30 12:50
Thanks for reporting this issue. I wasn't able to reproduce this problem using this snack. Have you tried using the latest version? I am closing this for now. If you manage to reproduce please reply with example.

**Closed by adamgrzybowski** 2020-07-30 12:50 UTC
