### ISSUE TITLE
Getting "Value for right cannot be cast from String to Double" on latest build

### ISSUE THREAD

**Issue by sgup** [software-mansion/react-native-gesture-handler#1728] opened 2021-11-20 18:27 UTC
## Description

After updating my libraries and making sure the library is installed according to the instructions, I'm getting this error on Android (works on iOS).

### Screenshots

![Screenshot_1637432563](https://user-images.githubusercontent.com/404386/142737100-06415c81-add1-45fa-9da2-6ec588fc3f66.png)

## Steps To Reproduce

1. Updated packages
2. Modified `MainActivity.java` as per [these instructions](https://docs.swmansion.com/react-native-gesture-handler/docs/#updating-mainactivityjava)

### Expected behavior

For views to work.

### Actual behavior

First view works, then switching to any tab causes this error.

## Snack or minimal code example

n/a

## Package versions

- React: 17.0.2
- React Native: 0.66.2
- React Native Gesture Handler: 1.10.3
`"@react-navigation/native": "^6.0.6",`

**Comment by Moorkell** [comment] 2022-01-04 20:19
When we upgraded from 5, we got this error as well.  In our case, it was caused by gestureResponseDistance in StackNavigationOptions getting changed from a map to a number

**Comment by jakub-gonet** [comment] 2022-02-22 17:03
This is caused by passing a string value instead of a number to `hitSlop` property of PanGestureHandler. As @Moorkell said this may be related to other libraries changing API. This isn't the bug with RNGH so I'm closing it.

**Closed by jakub-gonet** 2022-02-22 17:03 UTC
Labels: Platform: Android, Area: Gesture handlers

**Comment by Sun-Woo-Kim** [comment] 2022-12-05 03:27
In my case, the problem was with using `@react-navigation/stack`

## solution
Change the library from
```
@react-navigation/stack
````
to 
```
@react-navigation/native-stack
```
