### ISSUE TITLE
expo web not working

### ISSUE THREAD

**Issue by code4muktesh** [software-mansion/react-native-gesture-handler#1816] opened 2022-01-11 08:29 UTC
Using this package with expo getting error while building for web

```
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'ComposedGestureType' (reexported as 'ComposedGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'ExclusiveGestureType' (reexported as 'ExclusiveGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:66
"export 'FlingGestureType' (reexported as 'FlingGesture') was not found in './handlers/gestures/flingGesture'
  64 | export { TapGestureType as TapGesture } from './handlers/gestures/tapGesture';
  65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
> 66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:70
"export 'ForceTouchGestureType' (reexported as 'ForceTouchGesture') was not found in './handlers/gestures/forceTouchGesture'
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
> 70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
  73 | export {
./node_modules/react-native-gesture-handler/lib/module/index.js:79
"export 'GestureStateManagerType' (reexported as 'GestureStateManager') was not found in './handlers/gestures/gestureStateManager'
  77 |   ExclusiveGestureType as ExclusiveGesture,
  78 | } from './handlers/gestures/gestureComposition';
> 79 | export { GestureStateManagerType as GestureStateManager } from './handlers/gestures/gestureStateManager';
  80 | export { NativeViewGestureHandler } from './handlers/NativeViewGestureHandler';
  81 | export type {
  82 |   RawButtonProps,
./node_modules/react-native-gesture-handler/lib/module/index.js:67
"export 'LongPressGestureType' (reexported as 'LongPressGesture') was not found in './handlers/gestures/longPressGesture'
  65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
> 67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:72
"export 'ManualGestureType' (reexported as 'ManualGesture') was not found in './handlers/gestures/manualGesture'
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
> 72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
  73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:71
"export 'NativeGestureType' (reexported as 'NativeGesture') was not found in './handlers/gestures/nativeGesture'
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
> 71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
  73 | export {
  74 |   ComposedGestureType as ComposedGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:65
"export 'PanGestureType' (reexported as 'PanGesture') was not found in './handlers/gestures/panGesture'
  63 | export { GestureObjects as Gesture } from './handlers/gestures/gestureObjects';
  64 | export { TapGestureType as TapGesture } from './handlers/gestures/tapGesture';
> 65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:68
"export 'PinchGestureType' (reexported as 'PinchGesture') was not found in './handlers/gestures/pinchGesture'
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
> 68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'RaceGestureType' (reexported as 'RaceGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:69
"export 'RotationGestureType' (reexported as 'RotationGesture') was not found in './handlers/gestures/rotationGesture'
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
> 69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'SimultaneousGestureType' (reexported as 'SimultaneousGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:64
"export 'TapGestureType' (reexported as 'TapGesture') was not found in './handlers/gestures/tapGesture'
  62 | export { GestureDetector } from './handlers/gestures/GestureDetector';
  63 | export { GestureObjects as Gesture } from './handlers/gestures/gestureObjects';
> 64 | export { TapGestureType as TapGesture } from './handlers/gestures/tapGesture';
  65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
```

## Steps To Reproduce

expo web 

## Package versions
- React:17.0.1
- React Native:0.64.3
- Expo:44.0.4
- React Native Gesture Handler:2.1.0

**Comment by jakub-gonet** [comment] 2022-01-11 10:54
This is a duplicate of #1786. You can apply [this patch](https://github.com/software-mansion/react-native-gesture-handler/commit/62e9eb66bced3b4c55042399d761baee7d961140) to fix those errors.

**Closed by jakub-gonet** 2022-01-11 10:54 UTC
