### ISSUE TITLE
Swipeable onSwipeableWillOpen not firing

### ISSUE THREAD

**Issue by cchbr** [software-mansion/react-native-gesture-handler#2400] opened 2023-02-01 13:26 UTC
### Description

According to the docs for Swipeable, onSwipeableWillOpen should be called when an action panel starts animating, but it's not. No matter how I implement it, it's always called after the animation has finished and the action is triggered.

I need to implement onSwipeableWillOpen to prevent the underlying onPress to be triggered when a user only partially swipes and then releases. I'm not sure if that's the expected behaviour of Swipeable, or if child onPress should not be triggered,

### Steps to reproduce

1. Implement Swipeable inside a GestureHandlerRootView, with two levels of TouchableOpacity children.
2. Swipe only partially on the Swipeable. The TouchableOpacity is triggered.
3. Implement onSwipeableWillOpen to be able to detect a swipe and prevent onPress from triggering.
4. onSwipeableWillOpen does not fire when swiping.

### Snack or a link to a repository

None

### Gesture Handler version

2.9.0

### React Native version

0.69.6

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by j-piasecki** [comment] 2023-02-06 09:08
I've tried to reproduce it but it seems to be working correctly for me. Keep in mind that the animation doesn't start until the gesture is finished, so the callback will not fire while you are still dragging the swipeable as you may still choose not to open it.

Here's the code I've tried:
```jsx
import React from 'react';
import { View } from 'react-native';

import { TouchableOpacity, Swipeable } from 'react-native-gesture-handler';

export default function Example() {
  return (
    <View style={{ flex: 1, backgroundColor: 'red' }}>
      <Swipeable
        onSwipeableWillClose={(dir) => {
          console.log('will close', dir);
        }}
        onSwipeableWillOpen={(dir) => {
          console.log('will open', dir);
        }}
        onSwipeableOpen={(dir) => {
          console.log('open', dir);
        }}
        onSwipeableClose={(dir) => {
          console.log('close', dir);
        }}
        leftThreshold={50}
        rightThreshold={50}
        renderLeftActions={() => {
          return <View style={{ flex: 1, backgroundColor: 'yellow' }} />;
        }}
        renderRightActions={() => {
          return <View style={{ flex: 1, backgroundColor: 'magenta' }} />;
        }}>
        <TouchableOpacity
          onPress={() => {
            console.log('press outer');
          }}>
          <View
            style={{
              width: '100%',
              height: 80,
              backgroundColor: 'blue',
            }}>
            <TouchableOpacity
              onPress={() => {
                console.log('press inner');
              }}
              containerStyle={{ width: 80, height: 80, alignSelf: 'center' }}>
              <View
                style={{ width: 80, height: 80, backgroundColor: 'white' }}
              />
            </TouchableOpacity>
          </View>
        </TouchableOpacity>
      </Swipeable>
    </View>
  );
}
```

**Comment by cchbr** [comment] 2023-02-07 20:22
I tested your example and it's shows the same behaviour. 

If I understand you correctly it's actually the intended behaviour that onSwipeableWillOpen fires **after** the swiping motion has been completed, which is very strange given it's naming and should probably be clarified in the documentation.
For the documentation

> onSwipeableWillOpen
> method that is called when action panel starts animating on open (either right or left).

In reality it's not called when the panel start animating, but after the swipe has been completed/animated.

It seems that there's no function that's called when the swipe motion starts, so I can't use it to block the onPress from triggering. 

Is it also the indented behaviour that the underlying onPress is triggered on every swipe gesture? There must be a way to have a component that has an onPress that triggers function A, and also a swipe callback that triggers function B (that doesn't trigger function A on an incomplete swipe).

**Comment by j-piasecki** [comment] 2023-02-08 12:19
> Is it also the indented behaviour that the underlying onPress is triggered on every swipe gesture?

I'm not sure I get what you mean, this is what it looks like for me:

https://user-images.githubusercontent.com/21055725/217527616-0bbc8886-c452-4520-8388-31a5831c1f6e.mp4

When the swipe gesture gets recognized, the underlying button gets canceled and the `onPress` doesn't fire. Is this different in your case?

**Comment by cchbr** [comment] 2023-02-10 09:53
I copied your example but the underlying doesn’t always get cancelled. Sometimes it’s cancelled, but most of the time it fires even though it’s a swipe.


https://user-images.githubusercontent.com/36848317/218060747-4c7a76cc-8f39-408c-bfc8-9dfab0796054.MOV

**Comment by j-piasecki** [comment] 2023-02-16 10:55
I will close the issue since you've solved the problem. Feel free to reopen it if you encounter a similar problem in the future.

**Closed by j-piasecki** 2023-02-16 10:55 UTC
Labels: Platform: Android, Platform: iOS, Missing repro
