### ISSUE TITLE
2.8.0 breaks on android. 2.7.1 works fine.

### ISSUE THREAD

**Issue by ethanneff** [software-mansion/react-native-gesture-handler#2301] opened 2022-10-31 00:03 UTC
### Description

```
BUILD FAILED in 1m 53s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > A problem occurred configuring project ':react-native-gesture-handler'.
      > Could not resolve all files for configuration ':react-native-gesture-handler:classpath'.
         > Could not resolve com.android.tools.utp:android-test-plugin-result-listener-gradle-proto:30.2.1.
           Required by:
               project :react-native-gesture-handler > com.android.tools.build:gradle:7.2.1
            > Could not resolve com.android.tools.utp:android-test-plugin-result-listener-gradle-proto:30.2.1.
               > Could not get resource 'https://plugins.gradle.org/m2/com/android/tools/utp/android-test-plugin-result-listener-gradle-proto/30.2.1/android-test-plugin-result-listener-gradle-proto-30.2.1.pom'.
                  > Could not GET 'https://jcenter.bintray.com/com/android/tools/utp/android-test-plugin-result-listener-gradle-proto/30.2.1/android-test-plugin-result-listener-gradle-proto-30.2.1.pom'.
                     > Read timed out

* Try:
```

### Steps to reproduce

upgrade to 2.8.0 from 2.7.1. run `yarn android`

### Snack or a link to a repository

n/a

### Gesture Handler version

2.8.0

### React Native version

0.67.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device model

simulator

### Acknowledgements

Yes

**Comment by j-piasecki** [comment] 2022-11-02 08:05
Have you tried it again recently? It seems like it might've been caused by [JCenter downtime](https://status.gradle.com/incidents/9740r6bzx438).

As a side note, if you're still using JCenter, you should consider using another repository, here's more info about it: https://developer.android.com/studio/build/jcenter-migration

**Comment by j-piasecki** [comment] 2022-11-16 08:20
I'll close the issue for now since the linked issue has ben fixed and the original author hasn't responded.

**Closed by j-piasecki** 2022-11-16 08:20 UTC
Labels: Platform: Android, Missing repro
