### ISSUE TITLE
ITMS-90809: Deprecated API usage - UIWebView

### ISSUE THREAD

**Issue by mdeveracoding** [software-mansion/react-native-gesture-handler#1008] opened 2020-03-16 21:25 UTC
All,

Did a recent push to the Apple store and received the message below:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020 . See https://developer.apple.com/documentation/uikit/uiwebviewfor more information.

When we do a grep for UIWebView under node modules we see UIWebView in binary files for react-native-gesture-handler.  Are there plans to remove UIWebView in react-native-gesture-handler?

Grep results (grep UIWebView -r node_modules/*):

Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/ModuleCache.noindex/11EFTSSB0BUOA/UIKit-1V5UHAPTOD24G.pcm matches

Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/ModuleCache.noindex/11EFTSSB0BUOA/modules.idx matches

Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/Index/DataStore/v5/records/EJ/UIWebView.h-17DCX353XRLEJ matches

Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/Index/DataStore/v5/units/UIKit-1V5UHAPTOD24G.pcm-35LZDCPFUDPTH matches

Thanks for any assistance.

**Comment by antpuleo2586** [comment] 2020-03-16 22:24
We have the same issue but Apple gives us a deadline of April 2020...

**Comment by rgbdelta** [comment] 2020-03-19 04:01
This is pretty high priority. Could someone address this soon?

**Comment by enigmablue** [comment] 2020-03-19 04:59
Have this issue too the Apr 2020 is new apps right? existing apps have dec 2020 or something

**Comment by elliscwc** [comment] 2020-03-24 06:41
Also having this issue, not sure what to do

**Comment by n-nitchevski** [comment] 2020-03-30 16:53
Is there any update on this issue?

**Comment by antpuleo2586** [comment] 2020-03-30 19:22
My issue was actually with another library. Anyone using react-native-ux-cam update to the latest version, as this solved the issue for me. 
See: https://stackoverflow.com/a/60615933/5608321

**Comment by upcwangying** [comment] 2020-04-04 02:46
Also having this issue, not sure what to do

**Comment by upcwangying** [comment] 2020-04-04 13:24
@Brad19 [react-native-gesture-handler#1008](https://github.com/software-mansion/react-native-gesture-handler/issues/1008)

**Comment by bpetrified** [comment] 2020-04-10 03:07
Hi, can anyone confirm if the latest version of this repo is clean from ITMS-90809: Deprecated API usage - UIWebView ?

**Comment by bpetrified** [comment] 2020-04-10 04:49
> My issue was actually with another library. Anyone using react-native-ux-cam update to the latest version, as this solved the issue for me.
> See: https://stackoverflow.com/a/60615933/5608321

So the grep result of showing "UIView" related in binary should not trigger ITMS-90809 warning right ?

**Comment by florismettey** [comment] 2020-04-22 09:19
I also had Apple ITMS-90809 warning (ITMS-90809: Deprecated API Usage UIWebview).
I'm using React Native 0.61.5 and react-native-gesture-handler 1.6.0
When I do `grep -r UIWebView node_modules/*`, here is the result:
`Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/ModuleCache.noindex/11EFTSSB0BUOA/UIKit-1V5UHAPTOD24G.pcm matches
Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/ModuleCache.noindex/11EFTSSB0BUOA/modules.idx matches
Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/Index/DataStore/v5/records/EJ/UIWebView.h-17DCX353XRLEJ matches
Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/Index/DataStore/v5/units/UIKit-1V5UHAPTOD24G.pcm-35LZDCPFUDPTH matches`
Do you know why there is still references of UIWebview in those binary files?

**Comment by asharma-cyc** [comment] 2020-04-24 08:58
> I also had Apple ITMS-90809 warning (ITMS-90809: Deprecated API Usage UIWebview).
> I'm using React Native 0.61.5 and react-native-gesture-handler 1.6.0
> When I do `grep -r UIWebView node_modules/*`, here is the result:
> 
> `Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/ModuleCache.noindex/11EFTSSB0BUOA/UIKit-1V5UHAPTOD24G.pcm matches Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/ModuleCache.noindex/11EFTSSB0BUOA/modules.idx matches Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/Index/DataStore/v5/records/EJ/UIWebView.h-17DCX353XRLEJ matches Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/Index/DataStore/v5/units/UIKit-1V5UHAPTOD24G.pcm-35LZDCPFUDPTH matches`
> 
> Do you know why there is still references of UIWebview in those binary files?

Also seeing the same output.

**Comment by pssgo** [comment] 2020-04-28 02:04
same issues

**Comment by DaniAkash** [comment] 2020-04-28 04:41
The deadline approaches in two days, any updates on the fix?

**Comment by vadavallipavan** [comment] 2020-05-01 09:12
Any updates here please, TestFlight updates are now being rejected by Apple

**Comment by phyng** [comment] 2020-05-01 11:56
Recently we have the same issue, we use react-native-gesture-handler@1.5.6, but finally, we upgrade other lib and fix ITMS-90809. so I think react-native-gesture-handler does not trigger ITMS-90809.

**Comment by vadavallipavan** [comment] 2020-05-01 12:31
> Recently we have the same issue, we use react-native-gesture-handler@1.5.6, but finally, we upgrade other lib and fix ITMS-90809. so I think react-native-gesture-handler does not trigger ITMS-90809.

we are currently on 1.5.1 will update to 1.5.6 and double check . Thanks for your update

**Comment by bpetrified** [comment] 2020-05-02 08:41
> Recently we have the same issue, we use react-native-gesture-handler@1.5.6, but finally, we upgrade other lib and fix ITMS-90809. so I think react-native-gesture-handler does not trigger ITMS-90809.

Thank you for your update!

**Comment by upcwangying** [comment] 2020-05-04 00:06
I updated all the dependencies and still get the same issue

**Comment by bpetrified** [comment] 2020-05-04 01:41
> @bpetrified I updated all the dependencies and still get the same issue. I use 1.6.1

Are there any other libs in your project that might cause this warning ?

**Comment by upcwangying** [comment] 2020-05-04 01:49
@bpetrified Nope！

**Comment by vadavallipavan** [comment] 2020-05-04 02:28
> > Recently we have the same issue, we use react-native-gesture-handler@1.5.6, but finally, we upgrade other lib and fix ITMS-90809. so I think react-native-gesture-handler does not trigger ITMS-90809.
> 
> we are currently on 1.5.1 will update to 1.5.6 and double check . Thanks for your update

1.6.1  worked all good. . Thanks

**Comment by upcwangying** [comment] 2020-05-04 02:39
@vadavallipavan @bpetrified  I re-run the command `grep -r UIWebView node_modules/* > wv.txt` and I get the following information.  There is no information related to this dependency now

```
node_modules/create-react-class/node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
node_modules/create-react-class/node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
node_modules/jsc-android/dist/include/JSContextPrivate.h:/*! @abstract The delegate the context will use when trying to load a module. Note, this delegate will be ignored for contexts returned by UIWebView. */
node_modules/react-native-webview/README.md:- [7.0.1](https://github.com/react-native-community/react-native-webview/releases/tag/v7.0.1) - Removed UIWebView
node_modules/ua-parser-js/test/browser-test.json:        "ua"      : "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Mobile/14A456 QQ/6.5.3.410 V1_IPH_SQ_6.5.3_1_APP_A Pixel/1080 Core/UIWebView NetType/WIFI Mem/26",

```

**Comment by nilesh1883** [comment] 2020-05-05 18:45
Today my application got rejected with message: 

> ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. 

This is a blocker now.

**Comment by karpelcev** [comment] 2020-05-06 05:59
Well it's not because of this dependency @nilesh1883. I have this npm too and no rejections or warnings.

**Comment by nilesh1883** [comment] 2020-05-06 09:48
> Well it's not because of this dependency @nilesh1883. I have this npm too and no rejections or warnings.

Thank you for pointing that out: 

This library is not causing the issue, here are the links which helped me: 

https://github.com/invertase/react-native-firebase/issues/3018#issuecomment-566829775

https://stackoverflow.com/a/60615933/418074

**Comment by DaniAkash** [comment] 2020-05-07 03:05
The problem was present in the version 1.6.0 & earlier. After upgrading to 1.6.1 the reference to UIWebView is gone. This issue can be closed...

**Comment by marlti7** [comment] 2020-05-13 05:22
> The problem was present in the version 1.6.0 & earlier. After upgrading to 1.6.1 the reference to UIWebView is gone. This issue can be closed...

but i user rn 0.59.9 and react-native-gesture-handler need 1.4.0. how can i fix it?

**Comment by DaniAkash** [comment] 2020-05-13 22:30
@marlti7 you mean you can't install react-native-gesture-handler 1.6.1 in RN 0.59.9? 

If so, Would like to know the reason...

**Comment by nchase** [comment] 2020-05-19 13:25
> The problem was present in the version 1.6.0 & earlier. After upgrading to 1.6.1 the reference to UIWebView is gone. This issue can be closed...

@DaniAkash [This is the diff between 1.6.0 and 1.6.1](https://github.com/software-mansion/react-native-gesture-handler/compare/1.6.0...1.6.1) – how sure are you that this library was the cause of your UIWebView issue?

**Comment by DaniAkash** [comment] 2020-05-19 20:11
> > The problem was present in the version 1.6.0 & earlier. After upgrading to 1.6.1 the reference to UIWebView is gone. This issue can be closed...
> 
> @DaniAkash [This is the diff between 1.6.0 and 1.6.1](https://github.com/software-mansion/react-native-gesture-handler/compare/1.6.0...1.6.1) – how sure are you that this library was the cause of your UIWebView issue? 
> 
> Edit: somehow the references found via `grep UIWebView -r node_modules/*` associated to react-native-gesture-handler disappeared after this update, which only appears to change a type definition according to github, so something more than what's displayed in github must have happened between 1.6.0 and 1.6.1
> 
> Here was the diff that I saw with `grep UIWebView -r node_modules/*`  after updating to 1.6.1:
> 
> ```diff
> node_modules/@types/react-native-fbsdk/index.d.ts:    * Displays the dialog in a UIWebView within the app.
> node_modules/create-react-class/node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
> node_modules/create-react-class/node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
> node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
> node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
> node_modules/jsc-android/dist/include/JSContextPrivate.h:/*! @abstract The delegate the context will use when trying to load a module. Note, this delegate will be ignored for contexts returned by UIWebView. */
> node_modules/react-addons-shallow-compare/node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
> node_modules/react-addons-shallow-compare/node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
> node_modules/react-native-fbsdk/js/FBShareDialog.js:   * Displays the dialog in a UIWebView within the app.
> - Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/ModuleCache.noindex/11EFTSSB0BUOA/UIKit-1V5UHAPTOD24G.pcm matches
> - Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/ModuleCache.noindex/11EFTSSB0BUOA/modules.idx matches
> - Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/Index/DataStore/v5/records/EJ/UIWebView.h-17DCX353XRLEJ matches
> - Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/Index/DataStore/v5/units/UIKit-1V5UHAPTOD24G.pcm-35LZDCPFUDPTH matches
> node_modules/react-native-webview/README.md:- [7.0.1](https://github.com/react-native-community/react-native-webview/releases/tag/v7.0.1) - Removed UIWebView
> ```

I'm as clueless as you are. We need some maintainers to answer this

**Comment by hengkx** [comment] 2020-05-21 16:13
@upcwangying same problem. How can I solve it?

**Comment by ishaquehassan** [comment] 2020-05-27 20:18
If anyone still having this issue, in my case it was a `framework` in my `Podfile` which i found using 
` grep -r UIWebView ios/*` 

Hope this helps!

**Comment by anuj-njoshi** [comment] 2020-06-06 10:33
How to fix having dame issue after grep -r UIWebView ios/*

**Comment by MahmoudShaeer** [comment] 2020-06-06 15:34
+1

**Comment by anuj-njoshi** [comment] 2020-06-07 09:26
Thos are using react-native <0.60.x 
https://github.com/facebook/react-native/issues/26255#issuecomment-623144903
solved my issue

**Comment by halabe15** [comment] 2020-07-19 21:13
Find [solution here!](https://github.com/react-native-community/react-native-webview/issues/819#issuecomment-660708548)

**Comment by jakub-gonet** [comment] 2020-07-21 12:42
I'm pretty sure the newest version of Gesture Handler doesn't use UIWebView in any place, so I'm closing this issue.

**Closed by jakub-gonet** 2020-07-21 12:42 UTC
Labels: build-or-config-issue, iOS
