### ISSUE TITLE
Swipeable not working on Android from Modal

### ISSUE THREAD

**Issue by JeremyBradshaw7** [software-mansion/react-native-gesture-handler#737] opened 2019-08-23 08:31 UTC
Swipeable is not working on Android when used inside a Modal (as provided by react-native-modal), unless I set `coverScreen={false}` on the Modal but that upsets its positioning in some cases. 

I'm on RN 0.59.10 and RNGH 1.3.0 (have also tried 1.4.0).

I think this is the same issue as #139, but I'm not sure.

**Comment by yelkamel** [comment] 2019-09-18 12:11
Same for me if someone have any idea

**Comment by cspicuzza** [comment] 2020-01-29 02:55
No RNGH Touchables are working for me inside a modal on Android.  RN Touchables do work though

```
react-native 0.61.5
react-native-modal 11.5.3
react-native-gesture-handler 1.5.3
```

**Comment by oferRounds** [comment] 2020-04-20 12:44
Did anyone find a solution?

**Comment by djhr** [comment] 2020-05-18 15:50
having same issue with `PanGestureHandler` on android when inside a modal provided by react-native

**Comment by jakub-gonet** [comment] 2020-09-03 18:12
Duplicate of #139.

**Closed by jakub-gonet** 2020-09-03 18:12 UTC
