### ISSUE TITLE
cannot find symbol    String overflow = ((ReactViewGroup) view).getOverflow();

### ISSUE THREAD

**Issue by uendar** [software-mansion/react-native-gesture-handler#666] opened 2019-07-01 10:31 UTC
cannot find symbol    String overflow = ((ReactViewGroup) view).getOverflow();

**Comment by jakub-gonet** [comment] 2020-07-21 13:16
Duplicate of #662

**Closed by jakub-gonet** 2020-07-21 13:16 UTC

**Comment by TivanDev** [comment] 2020-09-13 07:27
just run 
`npm install react-native-gesture-handler@1.0.5
`
and secend step
`npx jetify`

then react-native run-android
