### ISSUE TITLE
Error building with New Architecture

### ISSUE THREAD

**Issue by hoanglam10499** [software-mansion/react-native-gesture-handler#2119] opened 2022-07-08 03:43 UTC
## Description
Error in building using latest version of react-native-gesture-handler and react-native,

```
> Task :react-native-gesture-handler:configureNdkBuildRelease FAILED
C/C++: C:/Users/lam.nh/AppData/Local/Android/Sdk/ndk/21.4.7075529/build//../build/core/build-binary.mk:651: Android NDK: Module rngesturehandler_modules depends on undefined modules: folly_runtime
C/C++: C:/Users/lam.nh/AppData/Local/Android/Sdk/ndk/21.4.7075529/build//../build/core/build-binary.mk:664: *** Android NDK: Note that old versions of ndk-build silently ignored this error case. If your project worked on those versions, the missing libraries were not needed and you can remove those dependencies from the module to fix your build. Alternatively, set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies.    .  Stop.

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':react-native-gesture-handler:configureNdkBuildRelease'.
> [CXX1405] error when building with ndkBuild using C:\Users\lam.nh\Desktop\test68\node_modules\react-native-gesture-handler\android\src\main\jni\Android.mk: Build command failed.
  Error while executing process C:\Users\lam.nh\AppData\Local\Android\Sdk\ndk\21.4.7075529\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\lam.nh\Desktop\test68\node_modules\react-native-gesture-handler\android\src\main\jni\Android.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 NDK_OUT=C:\Users\lam.nh\Desktop\test68\node_modules\react-native-gesture-handler\android\build\intermediates\cxx\Release\d65f3214/obj NDK_LIBS_OUT=C:\Users\lam.nh\Desktop\test68\node_modules\react-native-gesture-handler\android\build\intermediates\cxx\Release\d65f3214/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++17 APP_PLATFORM=android-21 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=C:\Users\lam.nh\Desktop\test68\android\app\build/generated/source PROJECT_BUILD_DIR=C:\Users\lam.nh\Desktop\test68\android\app\build REACT_ANDROID_DIR=C:\Users\lam.nh\Desktop\test68\node_modules\react-native/ReactAndroid REACT_ANDROID_BUILD_DIR=C:\Users\lam.nh\Desktop\test68\node_modules\react-native/ReactAndroid/build APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

  C:/Users/lam.nh/AppData/Local/Android/Sdk/ndk/21.4.7075529/build//../build/core/build-binary.mk:651: Android NDK: Module rngesturehandler_modules depends on undefined modules: folly_runtime
  C:/Users/lam.nh/AppData/Local/Android/Sdk/ndk/21.4.7075529/build//../build/core/build-binary.mk:664: *** Android NDK: Note that old versions of ndk-build silently ignored this error case. If your project worked on those versions, the missing libraries were not needed and you can remove those dependencies from the module to fix your build. Alternatively, set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies.    .  Stop.

```

### Platforms

- [ ] iOS
- [x] Android
- [ ] Web

### Screenshots
![image](https://user-images.githubusercontent.com/37326429/177912262-6ded6fcf-327c-4e28-a4ab-4194a6848a67.png)

## Steps To Reproduce
1/ create new project RN 0.68.2
2/ install [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler)
3/ `newArchEnabled=true` in `gradlew.properties`
4/ run android

### Expected behavior
Success build

### Actual behavior
Fail build

## Package versions

"react": "17.0.2",
"react-native": "0.68.2",
"react-native-gesture-handler": "^2.5.0"

**Comment by Skullcan** [comment] 2022-07-11 17:34
I'm having the same problem.

**Comment by j-piasecki** [comment] 2022-07-12 07:17
Hi! Because of the fact that it's still very early in the new architecture adoption and some major changes between React Native 0.68 and 0.69 (and the fact that Reanimated will support the new architecture starting with RN 0.69), we decided to make Gesture Handler compatible with RN 0.69 without backwards compatibility (only on the new architecture, when using the old one it should work as expected). I'd recommend upgrading to RN 0.69, which should solve the problem.

**Comment by SergioAN007** [comment] 2022-07-15 00:34
> 

I'm having the same problem in windows and macOS
 "react": "18.0.0",
 "react-native": "0.69.1",
 "react-native-reanimated": "3.0.0-rc.0",
 "react-native-gesture-handler": "^2.5.0",


Log generated in macOS Monterey.

> Task :react-native-gesture-handler:configureNdkBuildRelease[arm64-v8a] FAILED
C/C++: fcntl(): Bad file descriptor
C/C++: /Users/sergio/Library/Android/sdk/ndk/21.4.7075529/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gesture-handler:configureNdkBuildRelease[arm64-v8a]'.
> [CXX1405] error when building with ndkBuild using /Users/sergio/Desktop/RNApp/node_modules/react-native-gesture-handler/android/src/main/jni/Android.mk: Build command failed.
  Error while executing process /Users/sergio/Library/Android/sdk/ndk/21.4.7075529/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/sergio/Desktop/RNApp/node_modules/react-native-gesture-handler/android/src/main/jni/Android.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=0 NDK_OUT=/Users/sergio/Desktop/RNApp/node_modules/react-native-gesture-handler/android/build/intermediates/cxx/Release/48191t5z/obj NDK_LIBS_OUT=/Users/sergio/Desktop/RNApp/node_modules/react-native-gesture-handler/android/build/intermediates/cxx/Release/48191t5z/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++17 APP_PLATFORM=android-21 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=/Users/sergio/Desktop/RNApp/android/app/build/generated/source PROJECT_BUILD_DIR=/Users/sergio/Desktop/RNApp/android/app/build REACT_ANDROID_DIR=/Users/sergio/Desktop/RNApp/node_modules/react-native/ReactAndroid REACT_ANDROID_BUILD_DIR=/Users/sergio/Desktop/RNApp/node_modules/react-native/ReactAndroid/build APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
  Android NDK: ERROR:/Users/sergio/Desktop/RNApp/node_modules/react-native-gesture-handler/android/src/main/jni/Android.mk:fb: LOCAL_SRC_FILES points to a missing file    
  Android NDK: Check that /Users/sergio/Desktop/RNApp/android/app/build/react-ndk/exported/arm64-v8a/libfb.so exists  or that its path is correct   
  
  fcntl(): Bad file descriptor
  /Users/sergio/Library/Android/sdk/ndk/21.4.7075529/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.

**Comment by j-piasecki** [comment] 2022-07-15 08:25
Hi @SergioAN007! Could you make sure that you have [those lines](https://github.com/facebook/react-native/blob/ef6ab3f5cad968d7b2c9127d834429b0f4e1b2cf/template/android/app/build.gradle#L203-L212) in your app `build.gradle`? If not, you add them and check whether it solves the problem. If you already have them, or adding them is not helping, then there's a chance that [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2126) will resolve the problem.

**Comment by SergioAN007** [comment] 2022-07-15 08:56
Hi @j-piasecki! Thanks for you reply. Iam using modified this part of gradle.

afterEvaluate {
    // If you wish to add a custom TurboModule or component locally,
    // you should uncomment this line.
    // preBuild.dependsOn("generateCodegenArtifactsFromSchema")
    android.applicationVariants.all { def variant ->
        def variantName = variant.name.capitalize()
        def preVariantBuildTask = tasks.findByName("pre${variantName}Build")

        // Due to a bug inside AGP, we have to explicitly set a dependency
        // between configureNdkBuild* tasks and the preBuild tasks.
        // This can be removed once this is solved: https://issuetracker.google.com/issues/207403732
        if (variantName.endsWith("Debug")) {
            preVariantBuildTask.dependsOn(packageReactNdkDebugLibs)
            configureNdkBuildDebug.dependsOn(preVariantBuildTask)
            reactNativeArchitectures().each { architecture ->
                tasks.findByName("configureNdkBuildDebug[${architecture}]")?.configure {
                    dependsOn(preVariantBuildTask.name)
                }
            }
        }
        if (variantName.endsWith("Release")) {
            preVariantBuildTask.dependsOn(packageReactNdkReleaseLibs)
            configureNdkBuildRelease.dependsOn(preVariantBuildTask)
            reactNativeArchitectures().each { architecture ->
                tasks.findByName("configureNdkBuildRelease[${architecture}]")?.configure {
                    dependsOn(preVariantBuildTask.name)
                }
            }
        }
    }
}

This needs for build different android flavors. Link for RN [issue](https://github.com/facebook/react-native/issues/33596)

I will try in the evening to compile the application with the standard gradle code

**Comment by fgagneten** [comment] 2022-07-16 18:23
Same issue here. @SergioAN007 Did you find a fix for that error?

**Comment by SergioAN007** [comment] 2022-07-18 04:38
Hi. I have success build my RN project with enabled fabric on macOS Monterey. 

In my case, the build error was due to the fact that I used the "assembleMainRelease" command, but need to first build with the command "react-native run-android --variant mainRelease". After that, you can build as usual - "assembleMainRelease"

I checked the options proposed by @j-piasecki  during assembly:
1. For buil different android flovers (assembleMainRelease - Main name of the flover) still need using this gradle [fix](https://github.com/facebook/react-native/issues/33596#issuecomment-1103577770)
2. Using [PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2126)  is very helpful. Allows you to create only the specified application architectures, which significantly saves time for assembly. Today, not all libraries support this feature, so the chance of getting errors when specifying the desired build architecture and build parameter "--active-arch-only" is quite high

In windows i have [error](https://github.com/facebook/react-native/issues/34084) when building hermes, using Build Tools for Visual Studio 2022 last version. Maybe need install Visual Studio with full C++ support, or something else

Environment:

macOS Monterey
"react": "18.0.0",
"react-native": "0.69.1" + with [fix](https://github.com/facebook/react-native/pull/34151/files/84aea1a6bf4e16625d8b78e6f34347cd828244d6#diff-9f1ec5621e9be76a8225dc77bab4cbb7dc2ec6d79cd6e4b54e0af5e2b8aa6a2a)
"react-native-reanimated": "3.0.0-rc.0",
"react-native-gesture-handler": "^2.5.0",

**Comment by fgagneten** [comment] 2022-07-20 23:03
I'm not using a custom flavor, I tried what you said but still having the same issue

**Comment by fgagneten** [comment] 2022-07-31 13:53
I was able to reproduce with RN 0.69.3 just running:

1.` react-native init AwesomeProject`
2. Make sure add the following dependencies:

    "dependencies": {
        "react": "18.0.0",
        "react-native": "0.69.3",
        "react-native-reanimated": "2.9.1",
        "react-native-safe-area-context": "^4.3.1",
        "react-native-screens": "^3.15.0",
        "react-native-animatable": "1.3.3",
        "react-native-gesture-handler": "^2.5.0"
      },

4. Run `yarn android --active-arch-only`

**Comment by Ralisson-Mattias** [comment] 2022-08-06 18:25
Same error here in linux

**Comment by fgagneten** [comment] 2022-08-06 22:24
I was able to fix the issue. It's related to react-native-safe-area-context. Here is the PR: https://github.com/th3rdwave/react-native-safe-area-context/pull/302

**Comment by j-piasecki** [comment] 2022-08-10 07:29
The same change is already in Gesture Handler as of https://github.com/software-mansion/react-native-gesture-handler/pull/2126. It will be included in the next release, meanwhile you can use `patch-package` to apply it in your projects.

**Closed by j-piasecki** 2022-08-10 07:29 UTC
Labels: Missing info, Platform: Android, Missing repro

**Comment by student513** [comment] 2023-03-11 04:24
still same error in `"react-native": "0.70.6"`
