### ISSUE TITLE
Not work on iOS when RN version is 6.0+

### ISSUE THREAD

**Issue by WWWWWWWolf** [software-mansion/react-native-gesture-handler#775] opened 2019-09-28 15:54 UTC
When using RN 6.0 or 6.0+, the dependency is auto linking, but this dependency is not support for auto linking, manual link is not supported, and it's not work on iOS, Android is OK.

**Comment by calintamas** [comment] 2019-10-02 08:41
https://github.com/kmagiera/react-native-gesture-handler/issues/686#issuecomment-510889111

**Comment by jakub-gonet** [comment] 2020-08-25 15:11
Duplicate of #686.

**Closed by jakub-gonet** 2020-08-25 15:11 UTC
Labels: iOS
