### ISSUE TITLE
pointerEvents="box-none" does not work on Animated.View on Android?

### ISSUE THREAD

**Issue by zabojad** [software-mansion/react-native-gesture-handler#1270] opened 2020-12-11 16:00 UTC
## Description

On Android, `pointerEvents="box-none"` does not work on `Animated.View`.

## Steps To Reproduce

1. Use an Animated.View over touchable content.

2. Set its `pointerEvent` to `"box-none"`

3. Content below the  Animated View will not be touchable on Android

### Expected behavior

Should work as on iOS, `pointerEvents` should be honored with Animated.View on android as well.

### Actual behavior

`pointerEvents` is not honored with Animated.View on Android.

## Snack or minimal code example

TO be provided soon.

## Package versions

- React Native: 0.63.3
- React Native Gesture Handler: 1.7.0

**Comment by jakub-gonet** [comment] 2021-08-16 03:57
Sorry for the late response.

I couldn't reproduce this issue so it may have more complex conditions to trigger or has been fixed in the newer versions (tested on 1.10.3).

```jsx
import * as React from 'react';
import { SafeAreaView, View, Animated } from 'react-native';
import { TapGestureHandler } from 'react-native-gesture-handler';

export default () => (
  <SafeAreaView style={styles.container}>
    <Animated.View pointerEvents="box-none">
      <TapGestureHandler onBegan={() => console.log('Touch')}>
        <View style={styles.rectangle} />
      </TapGestureHandler>
    </Animated.View>
  </SafeAreaView>
);

const styles = {
  container: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  rectangle: {
    backgroundColor: 'pink',
    width: 100,
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
};
```

If you come up with a repro example, please reply.

**Closed by jakub-gonet** 2021-08-16 03:57 UTC
