### ISSUE TITLE
Android crash : Tearing down gesture handler error

### ISSUE THREAD

**Issue by huurray** [software-mansion/react-native-gesture-handler#1365] opened 2021-02-16 01:13 UTC
## Description

Hi my anrdroid simulator is crashed sometimes.
and after i checked android native log, i've got this error

`[GESTURE HANDLER] Tearing down gesture handler registered for root view com.facebook.react.ReactRootView{8864868 V.E...... ......ID 0,0-1440,2672}`

how can i fix it?
there is no any clue without this..

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Gesture Handler: 1.10.1

**Comment by jakub-gonet** [comment] 2021-02-16 06:31
Duplicate of #1363.
Please answer in the original thread instead of creating new ones.

**Closed by jakub-gonet** 2021-02-16 06:31 UTC
