### ISSUE TITLE
Unsupported top level event type "onGestureHandlerStateChange" dispatched

### ISSUE THREAD

**Issue by jalajgoel** [software-mansion/react-native-gesture-handler#1222] opened 2020-11-02 12:19 UTC
My React Native app is crashing while opening the side menu.
Using expo version - 36
Android SDK version- 36

**package.json**

`
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "lint": "eslint --fix -c .eslintrc.js ./src/**/*.js"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.0",
    "@react-native-community/datetimepicker": "2.0.0",
    "@react-native-community/image-editor": "^2.2.0",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-native-community/netinfo": "~3.2.1",
    "@react-navigation/bottom-tabs": "^5.2.2",
    "@react-navigation/drawer": "^5.7.4",
    "@react-navigation/material-bottom-tabs": "^5.1.3",
    "@react-navigation/material-top-tabs": "^5.1.10",
    "@react-navigation/native": "^5.1.0",
    "@react-navigation/stack": "^5.2.1",
    "@sentry/react-native": "^1.9.0",
    "aws-amplify": "^2.3.0",
    "aws-amplify-react-native": "^3.2.3",
    "expo": "^36.0.0",
    "expo-camera": "~7.0.0",
    "expo-constants": "^7.0.0",
    "expo-image-manipulator": "~7.0.0",
    "expo-localization": "~7.0.0",
    "formik": "^1.5.8",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.27",
    "ramda": "^0.27.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-input-mask": "^2.0.4",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-app-link": "^1.0.0",
    "react-native-chooser": "^1.7.0",
    "react-native-collapsible": "^1.5.1",
    "react-native-elements": "^1.2.3",
    "react-native-gesture-handler": "~1.5.2",
    "react-native-image-resizer": "^1.1.0",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-modal-datetime-picker": "^8.9.3",
    "react-native-paper": "^3.6.0",
    "react-native-qrcode": "^0.2.7",
    "react-native-qrcode-svg": "^5.3.2",
    "react-native-reanimated": "~1.2.0",
    "react-native-safe-area-context": "~0.3.6",
    "react-native-screens": "~1.0.0-alpha.23",
    "react-native-selectme": "^1.2.3",
    "react-native-svg": "9.9.5",
    "react-native-svg-transformer": "^0.13.0",
    "react-native-tab-view": "^2.14.0",
    "react-native-web": "^0.11.7",
    "sentry-expo": "^3.0.2",
    "xdl": "github:expo/xdl",
    "yup": "^0.27.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^7.0.0",
    "eslint": "^6.8.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-react": "^7.18.3",
    "eslint-plugin-sonarjs": "^0.5.0"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "private": true
}
`

**app.json**

`
{
  "expo": {
    "name": "ActiveWitness",
    "slug": "active-witness-mobile",
    "scheme": "active-witness",
    "description": "Access Active Witness Security Cameras",
    "privacy": "public",
    "sdkVersion": "36.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "0.9.11",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#004485"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "assets/*"
    ],
    "ios": {
      "bundleIdentifier": "com.activeWitness.activeWitness",
      "buildNumber": "110",
      "icon": "./assets/icon.png",
      "supportsTablet": false,
      "requireFullScreen": false,
      "isTabletOnly": false,
      "infoPlist": {}
    },
    "android": {
      "package": "com.activeWitness.activeWitness",
      "versionCode": 110,
      "permissions": [
        "CAMERA"
      ],
      "icon": "./assets/icon.png"
    },
    "packagerOpts": {
      "config": "metro.config.js",
      "sourceExts": [
        "js",
        "jsx",
        "svg",
        "ts",
        "tsx"
      ]
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "spineor-ov",
            "project": "activewitness_dev",
            "authToken": "80a4d6ed2dbb47538076d0aafca309ac30b85b789fce427482c124251e4182ce"
          }
        }
      ]
    }
  }
}`

**Comment by jakub-gonet** [comment] 2020-11-02 14:04
This is basically a duplicate of #320 and #849.

Could you provide a small reproduction example? We can't really help you without that.

**Closed by jakub-gonet** 2020-11-02 14:04 UTC
