### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNGestureHandlerButton

### ISSUE THREAD

**Issue by sankomil** [software-mansion/react-native-gesture-handler#1438] opened 2021-04-23 03:25 UTC
## Description

I randomly get the Invariant Violation error. On reloading it disappears, until it appears again randomly down the line.

### Screenshots

Error shows up on Metro server terminal, app just freezes up. All I get is `Error: Invariant Violation: Tried to register two views with the same name RNGestureHandlerButton`

## Steps To Reproduce

1. Create a new react native project and add react-navigation, react-native-gesture-handler and other dependencies.

### Expected behavior
Components and screens should load normally without any errors.

### Actual behavior

Receive `Invariant Violation: Tried to register two views with the same name RNGestureHandlerButton` randomly.

## Package versions

- React: 17.0.1
- React Native: 0.63.4
- React Native Gesture Handler: 1.10.3
- React Navigation: 4.4.0
- "@storybook/addon-viewport": "^6.0.21"
- "@storybook/addon-actions": "^5.3.19",
- "@storybook/addon-links": "^5.3.19",
- "@storybook/addons": "^5.3.19",
- "@storybook/react": "^5.3.19",
- "@storybook/react-native": "^5.3.19",
- "@storybook/react-native-server": "^5.3.19",

**Comment by jakub-gonet** [comment] 2021-04-23 10:06
Does any of your dependencies create a second instance of React Native by any chance?

**Comment by sankomil** [comment] 2021-04-23 10:11
No, I don't think so. Is there a way I can check? I couldn't find anything in the lock file, other than a reference for safe area view which was used by react navigation and I had also added.

**Comment by jakub-gonet** [comment] 2021-04-23 10:23
I think the fastest way to check that is to add some logging on initializing RN. Try adding some logs in MainActivity / AppDelegate. If you'll see duplicated logs then something is creating a second instance of RN. RN isn't really suited to work this way so it crashes when trying to register native components.

You can also add some logging in `node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java`, for example in `getName()` method.

You can try removing navigation and using some other library that relies on native components (e.g. react-native-maps. react-native-fast-image and so on). If your app will crash then it's probably accidentally connected to RNGH.

Remember to clear caches and native builds after installing dependencies.

**Comment by jakub-gonet** [comment] 2021-04-23 10:24
I'd appreciate it if you could link to the repository reproducing this issue so I can check it on my own.

**Comment by sankomil** [comment] 2021-04-23 12:13
Unfortunately I am not allowed share the repo since it is not a personal project, but I am trying to create a stripped version of it that shows the error. I did however manage to do a log in MainActivity by adding this:
```
  @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        hideNavigationBar();
        updateUI();
        System.out.println("RN testing");
    }
```

And only received a single instance of the string in logcat.

**Comment by jakub-gonet** [comment] 2021-04-23 12:21
> Unfortunately I am not allowed share the repo since it is not a personal project, but I am trying to create a stripped version of it that shows the error.

That's what I meant, we just need something that can be used to debug this issue.

> And only received a single instance of the string in logcat. gradlew clean removes the local builds right?

Yes, have you tested if it logs one string on crash or after loading your app normally?

You can also run metro with --reset-cache (i.e. yarn start --reset-cache) and this should clear the bundle - doesn't matter when you change native code but it helps to resolve issues surprisingly often.

**Comment by sankomil** [comment] 2021-04-23 12:38
> Yes, have you tested if it logs one string on crash or after loading your app normally?
It logs a string after loading my app normally. It doesn't log anything at the time of crash.

> You can also add some logging in `node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java, for example in getName()` method.

It gives an error if I use Log or System.out. Is there another method I can use?

> You can also run metro with --reset-cache (i.e. yarn start --reset-cache) and this should clear the bundle - doesn't matter when you change native code but it helps to resolve issues surprisingly often.

That gave me an `Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)` and the app won't run. 

I tried to remove everything but the basic components and two screens, but couldn't replicate the error there. I am also using MobX state tree, but I don't think that is the cause really.

**Comment by jakub-gonet** [comment] 2021-08-16 06:55
Sorry for no response, I must've missed it.

If you still experience this problem, please reply.

**Comment by sankomil** [comment] 2021-08-16 14:31
Hi, the problem still persists.

**Comment by jakub-gonet** [comment] 2021-08-17 05:47
> It gives an error if I use Log or System.out. Is there another method I can use?

What error? For another method, you can add a field to this class, let's say named `counter`, increment it in RNGestureHandlerButtonViewManager c-tor and throw an exception when it's bigger than 1. Or you can add `console.log` after line here https://github.com/software-mansion/react-native-gesture-handler/blob/efc0f61fea9cc8d4498f7ea9e282eaef6c08b552/src/components/GestureHandlerButton.tsx#L2

> I also found the following warning in Android Studio event log: Duplicate content roots detected: Path [C:/Users/khann/Documents/Kindo tests/kindo/node_modules/@react-native-community/picker/android] of module [RNStorybook.@react-native-community_picker] was removed from modules [RNStorybook.react-native-community_picker] could this be a possible reason?

I think the bigger problem here is the storybook that _may_ load the bundle twice. Could you try removing it from your project and checking if it resolves the problem?

**Comment by sankomil** [comment] 2021-08-17 07:27
> What error? For another method, you can add a field to this class, let's say named counter, increment it in RNGestureHandlerButtonViewManager c-tor and throw an exception when it's bigger than 1. Or you can add console.log after line here 

I put a `console.log` like so:
```
import { HostComponent, requireNativeComponent } from 'react-native';
import { RawButtonProps } from './GestureButtons';
console.log('comes here once')
const RNGestureHandlerButton: HostComponent<RawButtonProps> = requireNativeComponent(
  'RNGestureHandlerButton'
);

export default RNGestureHandlerButton;
```

And it was only printed once. I did this using Storybook right now.

**Comment by jakub-gonet** [comment] 2021-08-20 10:26
I think we can't do anything without a reproduction example.
If you have some time to do it, I'd really appreciate it. Then we can reopen the issue and figure out what's wrong - I'm pretty sure this isn't problem with RNGH.

I'm closing it for now since I can't repro it.

**Closed by jakub-gonet** 2021-08-20 10:26 UTC
Labels: Build or config issue
