### ISSUE TITLE
Natural swipe behaviour with touchpads

### ISSUE THREAD

**Issue by robertherber** [software-mansion/react-native-gesture-handler#1100] opened 2020-06-23 12:32 UTC
I'm looking for a natural behaviour on touchpads. Using the PanResponder requires pressing down on the touchpad and dragging while pressing - whereas I feel the natural behaviour would be swiping with two fingers. This is the case for both on the web implementation as well as natively on the iPad touchpad.

I'm building an implementation on top of ScrollView now - it's not fully optimal but the only way I've found to get a natural swipe on touchpads (and works for both iPad with touchpad and the web). The best would be if PanResponder would support this pattern out of the box with a configuration flag.

**Comment by jakub-gonet** [comment] 2021-05-10 07:17
Implemented in #1128.

**Comment by robertherber** [comment] 2021-05-10 08:18
> Implemented in #1128.

Yeah, for iPad! ;) Web would still be an open feature request! :)

**Comment by jakub-gonet** [comment] 2021-05-10 11:32
Oh, right. Reopening :>

**Comment by j-piasecki** [comment] 2024-10-15 14:42
This looks like a duplicate of https://github.com/software-mansion/react-native-gesture-handler/issues/800.

**Closed by j-piasecki** 2024-10-15 14:42 UTC
Labels: Feature request, Platform: Web, Area: Gesture handlers, BugBash 31.03

**Comment by robertherber** [comment] 2024-10-15 20:25
@j-piasecki Looks very much so.. 🤦‍♂️😂
