### ISSUE TITLE
Attempting to define property on object that is not extensible.

### ISSUE THREAD

**Issue by AbinSpericorn** [software-mansion/react-native-gesture-handler#1501] opened 2021-07-09 04:24 UTC
## Description

I'm using useAnimatedGestureHandler to map the gesture events

    <PanGestureHandler onGestureEvent={panGestureEvent}>
      <Animated.View style={[styles.container, rContainer]}>
        <Nearby translateY={translateY} {...{goToPage, HOME_LIST_HEIGHT}} />
        <Categories />
        <Header />
      </Animated.View>
    </PanGestureHandler>

All working perfect once i remove PanGestureHandler

### Screenshots
![image](https://user-images.githubusercontent.com/86065868/125023203-fc288a00-e09b-11eb-99c5-2e4d0ed3ad32.png)

## Steps To Reproduce

1.

## Package versions

- React:17.0.1
- React Native:0.64.2
- React Native Gesture Handler:1.10.3
- React Native Reanimated:2.0.0

**Comment by jakub-gonet** [comment] 2021-08-11 16:23
Could you please provide a link to repro so I can test it? Also, try using the newest Reanimated, it's possible that this issue has been already resolved.

**Comment by Gentlee** [comment] 2021-09-14 18:19
I have the same issue, opened it in RN repo with code examples:

https://github.com/software-mansion/react-native-reanimated/issues/2426

**Comment by galgord** [comment] 2021-09-15 19:26
I have the same issue following for solution

**Comment by piaskowyk** [comment] 2021-09-16 08:13
Hey everyone! 👋
Actually, this is not a bug. I explained the problem here: https://github.com/software-mansion/react-native-reanimated/issues/2426#issuecomment-920683754

**Comment by jakub-gonet** [comment] 2021-09-16 08:18
Well, it's Reanimated "issue" anyway. Closing.

**Closed by jakub-gonet** 2021-09-16 08:18 UTC
Labels: Area: Gesture handlers, Library: Reanimated
