### ISSUE TITLE
Extending RectButton throw an error

### ISSUE THREAD

**Issue by fedehappy** [software-mansion/react-native-gesture-handler#839] opened 2019-11-18 16:49 UTC
Hello. I'm trying to extend the RectButton in order to automatically add some style and customize a bit. But it returns me an issue. If I call it normally it works well.
Am I doing something wrong?

This is the main function

```
import {RectButtonCustom} from '../Touchables/Touchables';

<View style={styles.container}>
                    <RectButtonCustom
                        onPress={add}
                        style={styles.touchable}
                    >
                        <View style={[styles.holder, styles.action]} accessible>
                            <Text style={styles.text}>{"ADD"}</Text>
                            <Icon type="MaterialIcons"
                                  name="add-circle"
                                  style={styles.icon}
                            />
                        </View>
                    </RectButtonCustom>
                </View>
```
And this is the function I'm trying to create
```
import {RectButton} from 'react-native-gesture-handler';

export const RectButtonCustom = ({children, onPress}) => {
    return(
        <View style={styles.container}>
            <RectButton
                onPress={onPress}
                style={styles.touchable}
            >
                {children}
            </RectButton>
        </View>
    )
};

**Comment by jakub-gonet** [comment] 2020-08-24 14:07
`RectButton` crashes when passed an array of components.

May be duplicate of #711.

**Closed by jakub-gonet** 2020-08-24 14:07 UTC
