### ISSUE TITLE
React Native Error: TypeError: null is not an object _RNGestureHandlerModule.default.Direction

### ISSUE THREAD

**Issue by ratimaisuradze** [software-mansion/react-native-gesture-handler#835] opened 2019-11-13 08:06 UTC
I have tried many ways to fix this error but all attempts have failed.
>  - FOR ANDROID NOT IOS.

[enter image description here][1]

  [1]: https://i.stack.imgur.com/aVPad.png

I was trying for android. I found bug **react-native-gesture-handler** buy i don't know how to fix it.  

I am following this instruction  step by step https://reactnavigation.org/docs/en/getting-started.html  

I tried linking the react-native-gesture-handler manual. and also tried unlinked. 
I made **react-native.config.js** with code 

    exports = {
        dependencies: {
          'react-native-gesture-handler': {
            platforms: {
              android: null,
              ios: null,
            },
          },
        },
      };

I am using System:
   

     OS: Linux 5.3 Arch Linux undefined
        CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
        Memory: 16.06 GB / 31.21 GB
        Shell: 5.0.11 - /bin/bash
      Binaries:
        Node: 12.13.0 - /usr/bin/node
        Yarn: 1.19.1 - /usr/bin/yarn
        npm: 6.12.1 - /usr/bin/npm
        Watchman: 4.9.0 - /usr/local/bin/watchman
      npmPackages:
        react: 16.9.0 => 16.9.0 
        react-native: 0.61.4 => 0.61.4 
      npmGlobalPackages:
        react-native-cli: 2.0.1
    
    "react-navigation": "^2.18.2",
    "react-navigation-stack": "^1.10.3"

>  - FOR ANDROID NOT IOS.

**Comment by ratimaisuradze** [comment] 2019-11-13 08:31
https://stackoverflow.com/questions/58832672/react-native-error-typeerror-null-is-not-an-object-rngesturehandlermodule-def

**Comment by marlon-wiprud** [comment] 2019-11-21 21:16
Any resolution on this?

**Comment by enieber** [comment] 2019-11-22 15:18
@ratimaisuradze try update `react-navigation` with last version of `react-native-gesture-handler`

**Comment by AboutReact** [comment] 2019-11-22 15:21
Hey can you please have a look at [Swipe Gestures not Working in Android- React Native Gesture Handler](https://aboutreact.com/swipe-gestures-not-working-in-android/)

**Comment by vokhuyetOz** [comment] 2019-12-06 02:15
`import 'react-native-gesture-handler'
`
have you added it in the top of your index.js file?

**Comment by hangfangBio** [comment] 2020-03-05 09:11
I had same issue. Any resolution on this?   For Android not IOS.

**Comment by huangxiaojingCN** [comment] 2020-03-05 09:48
I had same issue. Any resolution on this?  For Android not IOS.

![image](https://user-images.githubusercontent.com/20080084/75969139-74f85e80-5f09-11ea-9205-f1c3429623d8.png)

**Comment by jakub-gonet** [comment] 2020-07-25 13:43
Duplicate of #494.

**Closed by jakub-gonet** 2020-07-25 13:43 UTC
