### ISSUE TITLE
Few latest release versions(2.15.0, 2.16.0, 2.16.1, 2.16.2) causing iOS build crash, version 2.14.1 is fine

### ISSUE THREAD

**Issue by badeggg** [software-mansion/react-native-gesture-handler#2927] opened 2024-05-30 07:19 UTC
### Description

When I update react-native-gesture-handler version, iOS build crashes. `2.14.1` --> `2.15.0/2.16.0/2.16.1/2.16.2`
After a little digging, the causing line is [here](https://github.com/software-mansion/react-native-gesture-handler/blob/921a9b2af4579021c5ca4ff40108e208683435b5/apple/RNGestureHandlerModule.mm#L102). Since I noticed that when I change this line back to 
```mm
        auto shadowNode = arguments[0].asObject(runtime).getHostObject<ShadowNodeWrapper>(runtime)->shadowNode;
```
which is identical in version 2.14.1 [here](https://github.com/software-mansion/react-native-gesture-handler/blob/55007fbd7a8430c22e38d0dc1789ab73648d5130/ios/RNGestureHandlerModule.mm#L99), iOS builds ok.

Crash report view:
![image](https://github.com/software-mansion/react-native-gesture-handler/assets/10908996/aa816624-c496-413c-be83-6d556328e89b)

Crash report file:
[c1.txt](https://github.com/software-mansion/react-native-gesture-handler/files/15495046/c1.txt)

### Steps to reproduce

1. Clone https://github.com/Expensify/App, I am on `2a7d5d497ebec61171c7033ff85cdd0731d710c5` which is main branch status for now
2. Upgrade react-native-gesture-handler version to version 2.16.2
3. Follow [steps](https://github.com/Expensify/App?tab=readme-ov-file#running-the-ios-app-) to start iOS app
4. You will notice build crash

### Snack or a link to a repository

https://github.com/badeggg/expensify-app

### Gesture Handler version

2.16.2

### React Native version

0.73.4

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by j-piasecki** [comment] 2024-06-03 09:49
Our current policy regarding the new architecture support is to support only the most recent version, which at the time of writing is 0.74. The crash you're describing is caused by a breaking change between RN 0.73 and 0.74.

I see you were able to work around it by using a patch. I would recommend using that until the[ PR that upgrades Expensify to 0.74](https://github.com/Expensify/App/pull/40548) is merged.

**Closed by j-piasecki** 2024-06-03 09:49 UTC
Labels: Platform: iOS, Repro provided
