### ISSUE TITLE
PinchGestureHandler and PanGestureHandler not working simultaneously 

### ISSUE THREAD

**Issue by IsaacGluck** [software-mansion/react-native-gesture-handler#927] opened 2020-01-21 04:11 UTC
Thanks in advance for the help!
Please let me know if I can provide any extra information!

- Platform: `iOS`
- sdkVersion: `35.0.0`

Refs:
```
  this.panHandler = React.createRef();
  this.pinchHandler = React.createRef();
```

Handlers:
```
  const scale = new Animated.Value(1);
  const onZoomEvent = (zoomeEvent) => {
    if (zoomeEvent.nativeEvent.scale >= 1) {
      return Animated.event([{
        nativeEvent: {
          scale,
        },
      }])(zoomeEvent);
    } else {
      return Animated.event([{ nativeEvent: { scale: 1 } }])(zoomeEvent);
    }
  };
  const onZoomStateChange = (event) => {
    if (event.nativeEvent.oldState === State.ACTIVE) {
      Animated.spring(scale, {
        toValue: 1,
      }).start();
    }
  };

  const translateX = new Animated.Value(0);
  const translateY = new Animated.Value(0);
  const handlePanEvent = (panEvent) => {
    return Animated.event(
      [{ nativeEvent: { translationX: translateX, translationY: translateY } }],
    )(panEvent);
  };
  const onPanStateChange = (event) => {
    if (event.nativeEvent.oldState === State.ACTIVE) {
      Animated.spring(translateX, {
        toValue: 0,
      }).start();
      Animated.spring(translateY, {
        toValue: 0,
      }).start();
    }
  };
```

JSX:
```
  <PinchGestureHandler
    ref={this.pinchHandler}
    simultaneousHandlers={this.panHandler}
    onGestureEvent={onZoomEvent}
    onHandlerStateChange={onZoomStateChange}
  >
    <Animated.View>
      <PanGestureHandler
        ref={this.panHandler}
        simultaneousHandlers={this.pinchHandler}
        minPointers={2}
        onGestureEvent={handlePanEvent}
        onHandlerStateChange={onPanStateChange}
      >
        <Animated.View>
          <Animated.Image
            source={{ uri: meme.get('url') }}
            style={{
              width: displayWidth,
              height: displayHeight,
              transform: [{ scale }, { translateX }, { translateY }],
            }}
            resizeMode="contain"
          />
        </Animated.View>
      </PanGestureHandler>
    </Animated.View>
  </PinchGestureHandler>
```

**Comment by abandohess** [comment] 2020-01-21 04:13
+1 having same issue

**Comment by Enoinoo** [comment] 2020-02-19 15:09
Having the same issue trying to use `PanGestureHandler` for dragging movement and `PinchGestureHandler` for zooming. 

Is there a fix for this yet?

**Comment by Enoinoo** [comment] 2020-02-24 14:30
I think this works fine on Android, but not on iOS.

**Comment by german970814** [comment] 2020-03-13 21:21
The issue is present on `iOS` version `13.3`. Any workaround about it?

**Comment by zulkarnainshariff** [comment] 2020-04-05 21:47
I had a problem with this too, solved it by putting a flex: 1 to all the <Animated.View>

**Comment by Enoinoo** [comment] 2020-04-17 16:11
> I had a problem with this too, solved it by putting a flex: 1 to all the <Animated.View>

I just tried this but the view just disappears.

**Comment by viveKing21** [comment] 2020-06-07 08:39
> I think this works fine on Android, but not on iOS.

nah its not working on android, 


import React from 'react'
import {View,Image,Animated, Button} from 'react-native'
import {PinchGestureHandler} from 'react-native-gesture-handler'
export default function pinchZoom(){
const scale=React.useRef(new Animated.Value(1)).current;
const HandlePinch=new Animated.event(
  [{nativeEvent:{scale}}]
  ,
  {
    useNativeDriver: false
  })
const anime=new Animated.ValueXY(0,0)
    return(
      <View style={{flex:1}}>
      <PinchGestureHandler onGestureEvent={HandlePinch}>
         <Animated.Image source={{uri:'https://i.ytimg.com/vi/Z4ls0-ZGnU4/maxresdefault.jpg'}}
         style={{height:250,width:'100%',transform:[{scale}]}}
         />
      </PinchGestureHandler>

      </View>
    )
 
}



its not even moving, dont know what im doing wrong help plz,

**Comment by majonathany** [comment] 2020-08-27 18:23
Any fix yet?

**Comment by jakub-gonet** [comment] 2020-09-03 13:39
Could you provide a _minimal, working_ example in form of [snack](https://snack.expo.io/), repo, or code block here?

**Comment by wadewadewadewadewadewade** [comment] 2020-09-16 03:03
I don't know if it helps, but I'm having a similar issue, and I've made a snack that can reproduce it...sort of...

https://snack.expo.io/@aproximation/react-native-draggable

My actual Android 9 device is behaving the way iPhone 8 in emulation is behaving on that snack: the first drag is jerky but sort of works, and subsequent drags have no animation, and the object just appears at the new destination when you release the mouse.

I tried to update the README for that snack to describe what I'm seeing

**Comment by RahulRijhwani** [comment] 2021-02-24 14:16
I am stuck at same issue 
Any update

**Comment by vivrkerror404** [comment] 2021-06-05 05:10
I am using PanResponder and pinch GestureHandler and faced the same issue and I fixed it by including a condition(gestureState.numberActiveTouches) in onStartShouldSetPanResponder value inside PanResponder.create() below is my code
eg:-
gestureState.numberActiveTouches  = 1 means touch event
gestureState.numberActiveTouches  = 1 means pinch event

      onStartShouldSetPanResponder: (evt, gestureState) => {if(gestureState.numberActiveTouches == 2){return false } else{return true} },

**Comment by vivrkerror404** [comment] 2021-06-05 05:12
I am using PanResponder and pinch GestureHandler and faced the same issue and I fixed it by including a condition(gestureState.numberActiveTouches) in onStartShouldSetPanResponder value inside PanResponder.create(),
 below is my code
eg:-
gestureState.numberActiveTouches  = 1 means touch event
gestureState.numberActiveTouches  = 2 means pinch event

      onStartShouldSetPanResponder: (evt, gestureState) => {if(gestureState.numberActiveTouches == 2){return false } else{return true} },

**Comment by seancheung** [comment] 2021-06-16 07:27
What about pinch and pan both with tow touched?(like the iOS photo markup app)

**Comment by DanleyCr7** [comment] 2021-06-28 17:18
react-native link react-native-gesture-handler

**Comment by amanda-t** [comment] 2021-07-09 20:21
I had the same issue where my simultaneous pinch/2-finger pan on an image worked on Android but not iOS, but then I found out it just doesn't work on my older first-generation iPhone SE. It does work on an iPhone XR. So maybe it's an older device thing? 

Made a simple Snack here: https://snack.expo.io/@amandatusing/simultaneous-pinch-and-zoom-gestures.

It's working on a Google Pixel 4a Android version 11 and an iPhone XR iOS 14.6.
On iPhone SE iOS 14.6 the gestures can't happen simultaneously. You can either 2-finger pan or pinch separately, but not together.

**Comment by innocentmasuki** [comment] 2023-02-06 15:59
> I am using PanResponder and pinch GestureHandler and faced the same issue and I fixed it by including a condition(gestureState.numberActiveTouches) in onStartShouldSetPanResponder value inside PanResponder.create(), below is my code eg:- gestureState.numberActiveTouches = 1 means touch event gestureState.numberActiveTouches = 2 means pinch event
> 
> ```
>   onStartShouldSetPanResponder: (evt, gestureState) => {if(gestureState.numberActiveTouches == 2){return false } else{return true} },
> ```

This fixed the problem for me

**Comment by niujianqiang123** [comment] 2023-12-01 08:42
react-native-gesture-handler v2.13.4 iOS v17.0 已修复，当我用option+mouse进行缩放，因为两个触点的中心，并没有发生移动，所以drag不会触发，当我用alt+mouse放置一个偏移的点，进行两个点缩放时，拖拽是生效的

**Comment by BrandonCao** [comment] 2024-01-31 22:23
Any update on this?

**Closed** 2024-10-15 14:20 UTC
Labels: Area: Gesture handlers
