### ISSUE TITLE
 null is not an object (evaluating '_RNGestureHandlerModule.default.Direction')

### ISSUE THREAD

**Issue by jalal-peimani** [software-mansion/react-native-gesture-handler#1166] opened 2020-08-14 06:35 UTC
## Description

I have problem with module 'react-navigation-stack' I got bellow error

ERROR TypeError: null is not an object (evaluating '_RNGestureHandlerModule.default.Direction') ERROR Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication) ERROR Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

### Screenshots
![image](https://user-images.githubusercontent.com/45000434/90220706-f55aae00-de1d-11ea-9510-2c8ec9e2e8fb.png)

## Steps To Reproduce

1.

### Expected beha
![image](https://user-images.githubusercontent.com/45000434/90220678-e83dbf00-de1d-11ea-9089-b5793d582ed4.png)
vior

## Package versions

- React:
- React Native:
- React Native Gesture Handler:

**Comment by jakub-gonet** [comment] 2020-08-14 10:19
Duplicate of #494

**Closed by jakub-gonet** 2020-08-14 10:19 UTC
Labels: bug

**Comment by jalal-peimani** [comment] 2020-08-15 08:53
I tried all of the solutions in  #494 issue 
but they are not work for me

**Comment by jakub-gonet** [comment] 2020-08-16 11:45
Have you followed the installation instructions of RNGH for android?

**Comment by jalal-peimani** [comment] 2020-08-18 18:29
I installed base bellow URL

https://reactnavigation.org/docs/getting-started

**Comment by jakub-gonet** [comment] 2020-08-20 12:04
Try following [RNGH installation instructions](https://docs.swmansion.com/react-native-gesture-handler/docs/next/#android).

**Comment by jalal-peimani** [comment] 2020-08-25 10:19
Thank you ...... I tried your solutions  and my problem has been solved

**Comment by koushikv04** [comment] 2021-01-06 16:42
Hi , I tried the fixes but still the issue persists

**Comment by jakub-gonet** [comment] 2021-01-06 17:33
@koushikv04, please describe what you did in order to setup RNGH and list your package versions.

**Comment by koushikv04** [comment] 2021-01-07 11:03
Hi @jakub-gonet I am running my project in Xcode 11.5 with react native version 0.61.4. The iOS project was working fine earlier but now there seems to be a problem running the app. I reinstalled the npm modules multiple times , I tried unlinking, uninstalling, reinstalling and relinking react-native-gesture-handler multiple times but doesn't seem to work. We basically use the gngesturehandler on the react native and it is added  as the first line in index file . Nothing seems to work . I installed the latest version 0.9.0 , it wasn't working and then I tried downgrading to 0.5.0 (which we were using earlier) and it still doesn't work.

**Comment by jakub-gonet** [comment] 2021-01-07 11:16
Did you try removing node_modules, yarn / npm cache, metro cache & Xcode cache? The latest (1.9.0) release should support autolinking so you don't have to link manually.

**Comment by koushikv04** [comment] 2021-01-07 11:33
yeah I did that ....I deleted node modules and caches and also I have cleaned the Xcode derived data as well but doesn't seem to work yet

**Comment by jakub-gonet** [comment] 2021-01-07 11:40
Well, it _should_ work, hard to say without any repro.
