### ISSUE TITLE
Deprecated use of UIManager

### ISSUE THREAD

**Issue by cristianoccazinsp** [software-mansion/react-native-gesture-handler#766] opened 2019-09-17 16:47 UTC
> Accessing view manager configs directly off UIManager via UIManager['getConstants'] is no longer supported. Use UIManager.getViewManagerConfig('getConstants') instead.

"react-native-gesture-handler": "1.4.1"
"react-native": "0.60.5"

All platforms.

**Comment by dimitarnestorov** [comment] 2019-09-20 16:43
Duplicate of #742

**Closed** 2019-12-19 14:55 UTC
